### PR TITLE
Update attime.py to use pytz

### PR DESCRIPTION
**Pull request by kokje**
Change instantiation of tzinfo object to match that in views.py because get_current_timezone() returns the LocalTimezone implementation of tzinfo which does not support 'localize' and results in an AttributeError

### CODE REVIEW

**Comment by kokje** [comment]
I think something similar also needs to be done on the 0.9.x branch, because we're currently on that and are facing this issue

**Comment by brutasse** [comment]
`get_current_timezone()` returns a proper timezone if `pytz` is installed. Are you actually seeing a `LocalTimezone` being returned with pytz installed?

**Comment by kokje** [comment]
Yup, I noticed it when I got this error while inspecting code from the UI
AttributeError: 'LocalTimezone' object has no attribute 'localize'. 
But since we're on 0.9.x which is pretty different I tried out these lines 
tzinfo = timezone.get_current_timezone()
tzinfo.localize(datetime.strptime(s,'%H:%M%Y%m%d'), daylight)
I was able to fix it by explicitly using pytz. I saw that's what views.py does and passes in the object so I thought I would change it here as well

**Comment by SEJeff** [comment]
@JeanFred: What do you think of this? Seems relevant to #1276

**Comment by obfuscurity** [comment]
Thanks!

**Comment by obfuscurity** [comment]
@brutasse @SEJeff any idea why this is failing the [lint test](https://travis-ci.org/graphite-project/graphite-web/jobs/82476434)? I grok the error:

```
/home/travis/build/graphite-project/graphite-web/webapp/graphite/render/attime.py:18:1: F401 'timezone' imported but unused
```

... but that seems incorrect. I see where we're calling `timezone` in [two](https://github.com/kokje/graphite-web/blob/ef5650c9c4deb2a8e1ff0f5a9ee1e312992edbaf/webapp/graphite/render/attime.py#L47) [different](https://github.com/kokje/graphite-web/blob/ef5650c9c4deb2a8e1ff0f5a9ee1e312992edbaf/webapp/graphite/render/attime.py#L70) places. We can add `# noqa` to the `import` but then what's the point of testing flake8?

**Comment by obfuscurity** [comment]
Gonna go ahead and noqa that for now. If it can be fixed "correctly" someone let me know.

**Comment by SEJeff** [comment]
@obfuscurity You sure about that?

[check this out](http://hastebin.com/piyomukehe.py)

No use of `timezone`

**Comment by SEJeff** [comment]
Is it possible there was a bad merge or something weird? When I clicked view full file in the changes section of this PR, it does show `timezone` being used. However, the current code in master clearly does not.

**Comment by obfuscurity** [comment]
Oh :poop:, you're right. I was looking at @kokje's master which was almost certainly behind. I'll fix that right now. thanks.

**Comment by obfuscurity** [comment]
Yup, it was in https://github.com/graphite-project/graphite-web/commit/b4ee01533b6d6f68bdfd9423574d25f7ed300126.

**Comment by SEJeff** [comment]
:)

**Pull request merged**
