### PR TITLE
Implement a config file for the render engine

### PR DESCRIPTION
**Pull request by cbowman0**
First two settings are:

1. Remove most recent datapoint in aggregate functions if there are any NULLs.

2. Sort the result set from fetchData so colors per series are consistent between graphs.

### CODE REVIEW

**Comment by cbowman0** [comment]
Rebased against master.

**Comment by obfuscurity** [comment]
Why do we need a new config file for graphite-web instead of just adding new settings to `local-settings.py` and `settings.py`?

**Comment by cbowman0** [comment]
It made sense to me 1.5 years ago when I wrote it up.  I'm attempting to remember that logic.  From what I recall, there aren't any similar items in settings.py or local-settings.py that manipulate content, so I mimicked graphTemplates.conf and dashboard.conf.  Whether that made sense then or makes the most sense now, I'll let you guys tell me.  If the consensus is we put them in settings.py, then that's a-ok with me.

**Comment by obfuscurity** [comment]
Unless there's a compelling reason for the new file, I think we should probably stick with the existing configs. Closing for now but if you can think of the original motivation please let us know.

**Pull request closed without merging**
