### PR TITLE
adding an integralByInterval() function

### PR DESCRIPTION
**Pull request by g76r**
This will do the same as integral() function, except resetting the total to 0 periodicaly.

For example:

     target=integralByInterval(company.sales.perMinute,"1d")&from=midnight-10days

This would start at zero on the left side of the graph, adding the sales each minute, and show the evolution of sales per day during the last 10 days.

### CODE REVIEW

**Comment by g76r** [comment]
Hi, is someone interested in reviewing and/or merging these changes ?
BTW, happy new year :-)

**Comment by g76r** [comment]
Hi, is someone interested in reviewing and/or merging these changes ?

**Comment by g76r** [comment]
Hi, is someone interested in reviewing and/or merging these changes ?

**Comment by g76r** [comment]
I've just rebased the PR against up to date master.
Is someone interested in reviewing and/or merging these changes ?

**Comment by g76r** [comment]
I've just rebased the PR against up to date master.
Is someone interested in reviewing and/or merging these changes ?

**Comment by obfuscurity** [comment]
❤️ Thanks @g76r!

**Comment by g76r** [comment]
thanks

**Pull request merged**
