### PR TITLE
Add ability to render PDFs

### PR DESCRIPTION
**Pull request by squarebracket**
Added the ability to render PDFs with the render API. There should be no additional requirements beyond what is already required.

### CODE REVIEW

**Comment by deniszh** [comment]
:+1:

**Comment by squarebracket** [comment]
Is there anything holding this back from getting merged?

**Comment by squarebracket** [comment]
...hello?

**Comment by deniszh** [comment]
LGTM, does anyone have concerns about merging this? 
@obfuscurity @brutasse @bmhatfield @mleinart ?
Will merge it otherwise. :)

**Comment by obfuscurity** [comment]
I haven't tested it but it LGTM. Ok to merge @deniszh. 👍

**Comment by deniszh** [comment]
I made a quick test, seems working. Merging. 🍖 
Thanks, @squarebracket, for your contribution, sorry for merge delay! 👍

**Comment by squarebracket** [comment]
No problem, I just wanted to make sure I wasn't missing anything!

**Pull request merged**
