### PR TITLE
Dashboard image refresh feedback

### PR DESCRIPTION
**Pull request by cbowman0**
Since PR #1845, there is no feedback on image refreshes.  This change gives feedback.  I can't claim this is the cleanest or best way to do it, so if someone has better ideas and/or methods please let me know.

### CODE REVIEW

**Comment by deniszh** [comment]
Codacy warning is nitpicking there.
LGTM.

**Comment by deniszh** [comment]
More reviewers needed, please.

**Comment by iksaif** [comment]
LGTM

**Comment by deniszh** [comment]
Thanks, @cbowman0 !

**Pull request merged**
