### PR TITLE
fix django 1.9 deprecation warnings, update django version check & re…

### PR DESCRIPTION
**Pull request by DanCech**
…move tests for old django

### CODE REVIEW

**Comment by obfuscurity** [comment]
This LGTM. In case anyone else (like me) was unaware, `django.conf.url.patterns()` was [deprecated in 1.8 and removed in 1.10](https://docs.djangoproject.com/en/1.8/internals/deprecation/#deprecation-removed-in-1-10).

**Comment by obfuscurity** [comment]
Anyone else in @graphite-project/committers want to review this before merging?

**Comment by iksaif** [comment]
LGTM

**Comment by deniszh** [comment]
LGTM

**Pull request merged**
