### PR TITLE
Polish the valid datetime

### PR DESCRIPTION
**Pull request by hzy001**
The length of the valid datetime may not be 13, therefore we polish it.

Signed-off-by: Hao Ziyu <haoziyu@qiyi.com>

### CODE REVIEW

**Comment by deniszh** [comment]
Kicked stuck test.
Agreed, the previous check was quite naive.

**Comment by DanCech** [comment]
I need to check, but I think this will break parsing for specifications like `8:50` when `now` is specified since that would now go through line 41 instead of line 82, and so with this patch would be relative to the current wall clock time rather than the `now` timestamp.

**Comment by DanCech** [comment]
@hzy001 do you have any examples of time specifications you're seeing that aren't being parsed properly?

**Comment by hzy001** [comment]
@DanCech 

First, I don't think it will break parsing for specifications like `8:50` when `now` is specified because the `s.replace(':','').isdigit()` will be False.

Second, I jusk try a set of examples and the parsing fails because the length of the string isn't 13, for example `8:5020171013` etc.

I just loose the restrict and I do think we need more advanced checks.

**Comment by DanCech** [comment]
@hzy001 I'm talking about the url parameter `&now=` which is fed into `parseATTime` as the parameter `now`.  I'll take a look at adding tests to make that clear, and whether we can relax the restriction without breaking things.

**Comment by DanCech** [comment]
Closing in favor of #2070

**Pull request closed without merging**
