### PR TITLE
Change remaining deprecated request.REQUEST

### PR DESCRIPTION
**Pull request by kviktor**
They didn't work because of this: https://docs.djangoproject.com/en/1.10/releases/1.7/#merging-of-post-and-get-arguments-into-wsgirequest-request

### CODE REVIEW

**Comment by deniszh** [comment]
Looks good on the first sight. /cc @obfuscurity ?

Did you try to run graphite on Django 1.10, @kviktor ?

**Comment by kviktor** [comment]
Nop, I tested it on 1.9 only.

**Comment by deniszh** [comment]
Looks good, will merge if no objections follow.

**Comment by obfuscurity** [comment]
No objections here.

**Comment by deniszh** [comment]
Merging then

**Pull request merged**
