### PR TITLE
hashing: better performances

### PR DESCRIPTION
**Pull request by iksaif**
See https://github.com/graphite-project/carbon/pull/726

### CODE REVIEW

**Comment by iksaif** [comment]
Wait for https://github.com/graphite-project/carbon/pull/727#issuecomment-355980527 to be merged, I'll include these changes too

**Comment by deniszh** [comment]
@iksaif @DanCech 
Looks like `get_nodes()` change is not backward compatible, all tests are failed. Then we need to roll it back in carbon too...

**Comment by iksaif** [comment]
Arf .. you're right, the order do matters because the replication factor is checked *after*. Please ignore this one for now, I'll send a fix for carbon.

**Comment by iksaif** [comment]
pushed tentative fix, let's see if travis is happy on both sides

**Comment by deniszh** [comment]
This works, cool! :)

**Pull request merged**
