### PR TITLE
Fix CeresReader fetch function to properly handle time frames that are in the future compared to the cached results

### PR DESCRIPTION
**Pull request by iliapolo**
This PR resolves issue #1671 for the master branch.

### CODE REVIEW

**Comment by deniszh** [comment]
👍 
Appreciating the test too!

**Comment by iliapolo** [comment]
@deniszh can you maybe explain why the ``codecov/patch`` check failed? what should i do?

**Comment by deniszh** [comment]
Good question, @iliapolo !
I'm not really sure TBH. Please ignore it for now. :)

**Comment by iliapolo** [comment]
Fair enough, ignored :)

**Comment by obfuscurity** [comment]
It's looking for more test coverage for the patch. Close enough, I wouldn't worry about that.

**Comment by deniszh** [comment]
Merging

**Pull request merged**
