### PR TITLE
Ensure WhiteNoise < 2.0.1 not used with Python 2.6

### PR DESCRIPTION
**Pull request by evansd**
WhiteNoise version 2.0.1 onwards now supports Python 2.6

### CODE REVIEW

**Comment by deniszh** [comment]
:+1: 
Thanks, @evansd !

**Comment by deniszh** [comment]
Backported that solution to 0.9.x in https://github.com/graphite-project/graphite-web/pull/1295

**Comment by evansd** [comment]
Shall I close this?

**Comment by deniszh** [comment]
No, I backported it only to 0.9.x, master branch needs to be fixed with this PR. Thanks, @evansd !

**Pull request merged**
