### PR TITLE
Dygraph and Rickshaw format types

### PR DESCRIPTION
**Pull request by obfuscurity**
This PR supersedes #1119, fixing some bugs and adding documentation for the new format types. Tested on my local Synthesize/master system.

### CODE REVIEW

**Comment by JeanFred** [comment]
This `renderView` method is quite a beast. What would you think of refactoring it by extracting methods for each render format − at least for the new ones introduced here? (Ultimately it could be nice to have one class per format and use polymorphism?).

**Comment by obfuscurity** [comment]
@JeanFred I agree that we should definitely look to refactor `views.py` (and frankly, `glyph.py` needs a lot of TLC). But for now I'd like to get these in and we can refactor as time permits.

@cbowman0 @SEJeff Do these tests look adequate to you? They're basically a copy of the existing `format=json` tests, but they already uncovered some bugs in the original implementation.

**Comment by obfuscurity** [comment]
Merging this in but please feel free to correct me if the tests are insufficient.

**Comment by cbowman0** [comment]
Tests look sufficient to me!

**Pull request merged**
