### PR TITLE
Feature/mon 160365 2

### PR DESCRIPTION
**Pull request by mayurmahajan**
This PR is to introduce a new field that reflects input target.

### CODE REVIEW

**Comment by deniszh** [comment]
Hello Mayur,
Could you please explain a bit why do you using this change?

**Comment by mayurmahajan** [comment]
Hi Deniszh, 

Sorry, for late response and thanks for following up. This PR is to fix this issue: https://github.com/graphite-project/graphite-web/issues/248.  The response "target" field sometimes does not show what was sent as in target field in the URL. This field is not making change in the response target field (to maintain backwards compatibility), however adding a new field input_target that reflects what's been sent as an input target.  I will add another commit to get the unit test checks pass.

**Comment by DanCech** [comment]
@mayurmahajan can you resolve the conflicts?

**Comment by deniszh** [comment]
Any objections to merge this?

**Comment by iksaif** [comment]
Could you add to the commit message an example of data before and after ?

**Pull request closed without merging**
