### PR TITLE
local_settings docs update.

### PR DESCRIPTION
**Pull request by b13n1u**
I have added to the docs some missing settings from the local settings example file. 

I'm not quite sure about the CARBONLINK_QUERY_BULK description.

### CODE REVIEW

**Comment by deniszh** [comment]
Hello @b13n1u,
Nice patch, I like it. But please remove 'CARBONLINK_QUERY_BULK' section, it's not supported it 1.0.x and later

**Comment by b13n1u** [comment]
Thats what I thought, removed.

**Comment by deniszh** [comment]
Looks good, will merge tomorrow and backport to 1.0.x

**Comment by gwaldo** [comment]
Those look like welcome additions to the Docs.  I'm happy with it.  Are there any objections to a merge, @graphite-project/committers ?

**Comment by deniszh** [comment]
merging

**Comment by iksaif** [comment]
LGTM

**Pull request merged**
