### PR TITLE
Fix issue #1454

### PR DESCRIPTION
**Pull request by drawks**
* Remove exception supression from remote_storage.FindRequest
* Include intervals.py from Main
* Update remote_storage.FindRequest.get_results to be compatible with both
  old and new metrics/find api pickle packet formats

### CODE REVIEW

**Comment by drawks** [comment]
FWIW this PR returns the exact same test failures as 0.9.x, those failures should be corrected, but I'm not sure I have a stomach for the archeology to find where they were introduced.

**Comment by deniszh** [comment]
s/1554/1454/g ?

**Comment by drawks** [comment]
@deniszh Yah, thanks. I fixed it

**Comment by mleinart** [comment]
I'm :+1: for not swallowing the exceptions but I really dont think we should be bringing in the intervals stuff into 0.9.x or shimming in compatibility to cluster with the master branch

**Comment by drawks** [comment]
The safe unpickler in 0.9.15 ALREADY referenced graphite.intervals, so it appears that it was the intention of that code for it to already be available. I've not done the archeology to find when/why intervals appeared in master or what the alternative to that type in a pickle packet should be or how that mapping should be implemented. 

I will say that if such a trivial change brings cross version api compat in a way that make federation work that it'd be a big win for facilitating changing versions in production without trying to cut everything over at once. It seems, to me, a good value from a marginally distasteful change.

**Comment by drawks** [comment]
So whats the consensus here? I'm fine running this patch out of tree to scratch my own itch, as it were. I still think this looks like the right way to handle this in tree. If bringing intervals from master is really that distasteful it seems that the unpickler code in 0.9.x should also have references to it scrubbed.

**Comment by mleinart** [comment]
Yeah, the unpickler code should be cleaned up - I'm sure that's just
copypasta

I'd still like to see that exception swallowing go away, but I remain
unconvinced that bringing in compatibility across major versions is a good
idea. Supporting cross-version clusters complicates debugging user problems
and could cause people silent breakage rather than a fail-fast break as
things in master change. It's also bad precedent to set - we need to be
able to break compatibility to move forward. For instance, supporting
archived timesteps in Ceres will require significant changes to
intervals.py (support for comparing intervals of different timesteps). We
already have a sort of hell keeping the changes that come in to 0.9.x added
to master, I'd rather us not start committing to going the other direction
too

**Comment by obfuscurity** [comment]
+1 to @mleinart's comment

**Comment by drawks** [comment]
K, fair. I'll rejigger this PR when I have a few moments free.

**Pull request closed without merging**
