### PR TITLE
settings: reduce default number of threads

### PR DESCRIPTION
**Pull request by iksaif**
See #1885

### CODE REVIEW

**Comment by deniszh** [comment]
`POOL_WORKERS_PER_BACKEND = 1`
But does reducing `POOL_WORKERS` to 1 making all pool thing useless?

**Comment by iksaif** [comment]
I think that's fine, you end up with between 2 and N threads (with N-1 being the number of backends). That's usually way enough since you're not going to process requests in parallel most of the time.

Remember that the total number of threads is `POOL_WORKERS_PER_BACKEND * len(CLUSTER_SERVERS) + POOL_WORKERS`.

**Comment by deniszh** [comment]
>Remember that the total number of threads is POOL_WORKERS_PER_BACKEND * len(CLUSTER_SERVERS) + POOL_WORKERS.

Cool! Maybe it's worth to mention that somewhere in https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example#L248-L262 ?

**Comment by iksaif** [comment]
Updated :)

**Comment by deniszh** [comment]
Cool! 👍

**Pull request merged**
