### PR TITLE
Coverage for graphite.whitelist

### PR DESCRIPTION
**Pull request by cbowman0**
I had this mostly together, so in light of issue #1569 and pull request #1570, I submit this for test cases before the wording changes.

* Fix graphite.whitelist.load_whitelist()
* Add test cases for show, add and remove

Of note, the load_whitelist() function was not working before this change.  If the preferred method is to read the blob in and use unpickle.loads(), then that can be done.

### CODE REVIEW

**Comment by gwaldo** [comment]
Thank you for this, @cbowman0

**Comment by cbowman0** [comment]
I adjusted the testing to be deterministic.  I would like someone else from @graphite-project/committers to confirm the changes to load_whitelist() is ok.

Once that is merged, I will help @gwaldo with adjusting the test cases to work with his wording changes, if required.

**Comment by obfuscurity** [comment]
@cbowman0 why the change from `unpickle` to `pickle`? The latter is intended as a safe alternative to the insecure pickle.

https://github.com/graphite-project/graphite-web/blob/af7c0c13889c59a192debcb3833643df3d394597/webapp/graphite/util.py#L159-L212

**Comment by cbowman0** [comment]
@obfuscurity Because it currently doesn't work.  Calls to load_whitelist() error with:
`AttributeError: type object 'SafeUnpickler' has no attribute 'load'`

**Comment by obfuscurity** [comment]
Ah right, we're loading from a file, not a string. Looks like a typo from https://github.com/graphite-project/graphite-web/commit/c198e5836970f0970b96498fcbe6fa83d90110cf. Yeah, this change looks good.

👍

**Comment by cbowman0** [comment]
Alternatively, we can do:
```
   buffer = open(settings.WHITELIST_FILE, 'rb').read()
   whitelist = unpickle.loads(buffer)
```
and add set to the PICKLE_SAFE set.  I can do that quickly, if that's preferred.

**Comment by obfuscurity** [comment]
@cbowman0 Yeah, good idea.

**Comment by cbowman0** [comment]
Done.  Once automated checks go green again, I'll merge it.

**Pull request merged**
