### PR TITLE
When creating DB do not use --run-sync-db

### PR DESCRIPTION
**Pull request by AlejandroRivera**
With `--run-sync-db`:
```
$ sudo PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
Operations to perform:
  Synchronize unmigrated apps: account, render, staticfiles, whitelist, metrics, url_shortener, dashboard, composer, events, browser
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table account_profile
    Creating table account_variable
    Creating table account_view
    Creating table account_window
    Creating table account_mygraph
    Creating table dashboard_dashboard
    Creating table dashboard_template
    Creating table events_event
    Creating table url_shortener_link
    Running deferred SQL...
Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 172, in handle
    self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 293, in sync_apps
    cursor.execute(statement)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
```

Without `--run-sync-db`:
```
$ sudo PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings
Operations to perform:
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
  Applying tagging.0001_initial... OK
  Applying tagging.0002_on_delete... OK
```

### CODE REVIEW

**Comment by deniszh** [comment]
I think you need to run python manage.py migrate auth
`PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate auth --settings=graphite.settings`
first - it will create auth relations, then `--run-syncdb` will work well.

**Comment by AlejandroRivera** [comment]
When i tried it myself without `auth` (and without `--run-syncdb`) it seemed to have created all the tables (including auth relations), since when i tried `--run-syncdb` right after, there were no issues.

At this point, i'm not sure what's the difference between:
```
PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate auth --settings=graphite.settings
```
and
```
PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings
```
but if you say that's the right way of creating the DB for the first time, i can make the change in the PR. I'll await confirmation.

**Comment by deniszh** [comment]
Well... I'm not a big Django expert, unfortunately. If `migrate` doing the same as `migrate auth` and `migrate --run-syncdb` then it's simpler - because it's a single command.
Maybe @brutasse knows?

**Comment by deniszh** [comment]
I spent some time with python3 and django 1.11. Looks like `migrate auth` and `migrate` behaves little better.

**Comment by AlejandroRivera** [comment]
> Looks like migrate auth and migrate behaves little better.

Sorry, i'm not sure i understand what you mean. Can you elaborate?

**Comment by deniszh** [comment]
@AlejandroRivera:
No, disregard that. What's your Django version?
Looks like `migrate auth` and `migrate --run-syncdb` works fine for 1.8.x, but cause troubles for 1.11

**Comment by AlejandroRivera** [comment]
My version is `1.9.13`

**Comment by deniszh** [comment]
TBH I didn't reproduce cases when `--run-sync-db` doesn't work, but simple `migrate` does. I'll prefer to keep  `--run-sync-db` in documentation, because it works well on empty db, but upgrade manual is still open question.

**Comment by AlejandroRivera** [comment]
@deniszh, do you have any ideas of who to tag so the discussion can take place? I do not :(

**Comment by DanCech** [comment]
I suspect the correct command varies by django version :( I'll do some digging and see what I can find out

**Comment by ploxiln** [comment]
This can be closed because #2425 was merged

**Pull request closed without merging**
