### PR TITLE
@Jjneely merge timeseries

### PR DESCRIPTION
**Pull request by deniszh**
During a rebalance of a consistent hash cluster, after a partition event
on a replication > 1 cluster, or in other cases we might receive
multiple TimeSeries data for a metric key. Merge them together rather
that choosing the "most complete" one.

Contains original work from @jjneely's https://github.com/graphite-project/graphite-web/pull/1293 and my changes for enable/disable merging through config variable.

### CODE REVIEW

**Comment by jjneely** [comment]
This looks great to me.  Thanks!

**Comment by deniszh** [comment]
Tested that on simple 2 node cluster - works now:
1. Creating local.random.diceroll3 metric on server1 - with values 1..5:
```shell
dzhdanov@graph001:/$ for x in 1 2 3 4 5; do echo "local.random.diceroll3 ${x} `date +%s`" | nc -q0 127.0.0.1 2103; sleep 60; done
dzhdanov@graph001:/$ whisper-dump.py /opt/graphite/storage/whisper/local/random/diceroll3.wsp | grep -A 10 'Archive 0 data'
Archive 0 data:
0: 1444641360,          1
1: 1444641420,          2
2: 1444641480,          3
3: 1444641540,          4
4: 1444641600,          5
5: 0,          0
6: 0,          0
7: 0,          0
8: 0,          0
9: 0,          0
```
After finishing that script run similar on node 2
2. Creating local.random.diceroll3 metric on server2 with values 6..10:
```shell
dzhdanov@graph002:~$ for x in 6 7 8 9 10; do echo "local.random.diceroll3 ${x} `date +%s`" | nc -q0 127.0.0.1 2103; sleep 60; done
dzhdanov@graph002:~$ whisper-dump.py /opt/graphite/storage/whisper/local/random/diceroll3.wsp | grep -A 10 'Archive 0 data'
Archive 0 data:
0: 1444641840,          6
1: 1444641900,          7
2: 1444641960,          8
3: 1444642020,          9
4: 1444642080,         10
5: 0,          0
6: 0,          0
7: 0,          0
8: 0,          0
9: 0,          0
```
4. Applying patch with MERGE_TIMESERIES=True
3. Checking Graph in Grafana:
screen shot 2015-10-12 at 12 30 35
4. Switching to MERGE_TIMESERIES=False on both nodes:
screen shot 2015-10-12 at 12 31 23

Please check and review - @jjneely @bmhatfield @obfuscurity @brutasse @SEJeff ?

**Comment by GoozeyX** [comment]
Is there any specific reason why this was not merged into the master branch?

**Comment by deniszh** [comment]
Yes. The completely different master code in "data retrieval" area. Still need to be ported there - but it will require more patches to port...
Sad but true.

**Comment by obfuscurity** [comment]
@deniszh @jjneely We absolutely need to get this into master. Is there anyone willing to take this on if we find a sponsor?

**Pull request merged**
