### PR TITLE
Trying to fix RTD builds for 0.9.x

### PR DESCRIPTION
**Pull request by deniszh**
Please see https://github.com/graphite-project/graphite-web/issues/677#issuecomment-150974416

### CODE REVIEW

**Comment by deniszh** [comment]
@obfuscurity @gwaldo @brutasse - could you please check - does it looks good and does it fix RTD build (merge/revert maybe) ?

**Comment by brutasse** [comment]
@deniszh great, I forgot that setup.cfg didn't have the `[install]` section anymore in master. Looks good, there's only a try/finally block around the `setup()` call: see what's done in master, we need to make sure the add/remove dance doesn't alter the file.

**Comment by deniszh** [comment]
Now looks better, @brutasse ?

**Comment by brutasse** [comment]
@deniszh :+1:

**Comment by brutasse** [comment]
Build passed. Thanks @deniszh! :sparkles: :zap:

**Comment by deniszh** [comment]
Cool! We are ready to finally "push the button"
push

**Comment by JeanFred** [comment]
This is beautiful. Great job @deniszh

**Comment by obfuscurity** [comment]
Indeed, great work @deniszh @brutasse. Nice to have this fixed (for a while anyways, lol).

**Pull request merged**
