### PR TITLE
add architecture diagram to faq.rst

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Blocking on a build issue in #1091.

**Comment by ryan-williams** [comment]
weirdly the build didn't originally fail here, I guess it didn't attempt to build the docs as of `0.9.x`?

**Comment by obfuscurity** [comment]
We don't have a docs-specific build here, I forget the reason.

**Comment by obfuscurity** [comment]
Looks good. http://graphite.readthedocs.org/en/0.9.x/faq.html

**Pull request merged**
