### PR TITLE
Add more coverage to dashboard

### PR DESCRIPTION
**Pull request by cbowman0**
Correct a bug in template if the dashboard-\<theme>.css does not exist.

Cover almost all cases with graphite/dashboard.

### CODE REVIEW

**Comment by cbowman0** [comment]
@JeanFred Is this more in line with best practice?

**Comment by JeanFred** [comment]
This  is great @cbowman0 ! Love it :)

**Comment by obfuscurity** [comment]
👍

**Comment by gwaldo** [comment]
:heart:

**Pull request merged**
