### PR TITLE
0.9.x use a dict to search for known TimeSeries in webapp

### PR DESCRIPTION
**Pull request by jjneely**
This can't be merged without #1293 unlike what Github says.

However, using a dict here instead of a list give a vast performance increase with large queries.

### CODE REVIEW

**Comment by jjneely** [comment]
or I guess this can me merged in lieu of #1293

**Comment by deniszh** [comment]
:+1:
Didn't have such big queries, but will try this patch tomorrow. Thanks!

**Comment by deniszh** [comment]
Yep,  it's better to add this commit to #1293 and close this one.

**Comment by jjneely** [comment]
#1293 is now updated.  Thanks!

**Pull request closed without merging**
