### PR TITLE
Properly format floats in a handful of functions

### PR DESCRIPTION
**Pull request by drcapulet**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Thank you for adding these tests. Dumb question but why not just use `%f` instead of `%g`?

**Comment by obfuscurity** [comment]
Disregard, `%g` definitely looks more suitable here.

**Comment by obfuscurity** [comment]
LGTM. @deniszh @SEJeff @cbowman0 Any concerns?

**Comment by cbowman0** [comment]
I have no concerns with it.

**Comment by JeanFred** [comment]
Looks good to me as well.

**Comment by deniszh** [comment]
:+1:

**Pull request merged**
