### PR TITLE
setup.py: make it works with python3 based tox.

### PR DESCRIPTION
**Pull request by iksaif**
Make tox work if it has been installed to use python3 (like
it is in recent ubuntu).

### CODE REVIEW

**Comment by deniszh** [comment]
👍

**Comment by obfuscurity** [comment]
I don't see any obvious regressions for Python 2.x but I wonder why we'd _want_ this in there? Are you running Graphite successfully with Python 3.x?

**Comment by iksaif** [comment]
I'm not running Graphite with Python 3, but my `tox` command seems to use python3 to run setup.py

**Comment by obfuscurity** [comment]
Maybe something wonky with your python environment? IMHO you should be [developing and running your tests in a virtualenv](http://graphite.readthedocs.io/en/latest/development.html#setting-up-a-development-environment) anyways.

**Comment by obfuscurity** [comment]
Regardless I don't see any problems with this going in for now with the expectation that One Day :tm: we'll support Python 3. 😜

**Comment by obfuscurity** [comment]
@iksaif I'm tempted to merge it, but given that it's largely an unnecessary change and that the same hasn't been submitted for the other projects, I'm going to pass on this for now. 

@deniszh You have any strong opinion on this?

**Comment by deniszh** [comment]
@obfuscurity - I also have no idea why this change is needed for @iksaif 
So - ¯\_(ツ)_/¯

**Comment by obfuscurity** [comment]
Ok I'm closing this one now but I'm gonna hold onto it like that last piece of bubble gum for when we really need it. :wink:

**Comment by iksaif** [comment]
To add more context: this change is needed to simply be able to run "tox" on modern systems (such as my ubuntu box where python3 is default). Running tox in a virtualenv works, but is kind of counter-intuitive because tox will then install more virtualenv to run the tests.

**Comment by obfuscurity** [comment]
Modern systems or not, Python 2.x is still a requirement for Graphite. Our own tox.ini requires Python 2.7 as the `basepython`.

**Pull request closed without merging**
