### PR TITLE
Query carbon cache when metrics not found in file system.

### PR DESCRIPTION
**Pull request by wooparadog**
For the circumstances when new metrics are not synced to file system, hence not found when querying.

Need help:

This is actually a hack, I don't have enough knowledge of how graphite-web is structured, so it needs a better way to get integrated into this project.

### CODE REVIEW

**Comment by deniszh** [comment]
An interesting feature, thanks, @wooparadog!
Not sure about realisation too... The separate reader looks like bit hackish, indeed.

Tests are broken because of docs again... we need to find out why...

**Comment by bmhatfield** [comment]
I think this is a step towards a great idea, but I think this PR misunderstands the problem slightly.

Graphite-web *already* queries carbon-cache for datapoints in the case where it's aware a metric exists. The problem is that this awareness purely comes from globbing the file system. 

Carbon-Cache doesn't support any sort of "list keys" or globbing behavior, so this PR will only fix the case where the full path to the metric is specified.

A more correct fix, I think, is to add list-keys or globbing type behavior to carbon-cache as part of the "metric find" functionality. Then graphite-web will know there's some uncommitted metrics in carbon-cache and will naturally attempt to retrieve them. 

On the carbon side, that lookup will need to be performant, as it will happen frequently.

**Comment by wooparadog** [comment]
Yeah, I realized that this implementation can't have lookup support. I'm working on carbon-cache to add a new `DrainStrategy` so that new metrics can get written faster.

**Comment by wooparadog** [comment]
Closing this idae now...

**Comment by deniszh** [comment]
@wooparadog - you can also check these PRs:
https://github.com/graphite-project/carbon/pull/419
https://github.com/graphite-project/graphite-web/pull/1277
Both need to be ported to master, though - but I tested that on 0.9.x - at least metric flushing works.

**Pull request closed without merging**
