### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by deniszh**
- some changes for tools and config-web pages in the documentation.

### CODE REVIEW

**Comment by DanCech** [comment]
Looks good, not sure how up to date those carbon-api benchmarks are.  AFAIK graphite-remote-adapter doesn't (yet) support tags so I wouldn't call it "fully featured"

**Comment by deniszh** [comment]
>Looks good, not sure how up to date those carbon-api benchmarks are.

Yep, that's why I put "In some benchmarks". Benchmarks are lie, everybody knows that.

>AFAIK graphite-remote-adapter doesn't (yet) support tags so I wouldn't call it "fully featured"

I hope they will finish it soo, right, @iksaif ? :)

**Comment by deniszh** [comment]
We can add some fixes later, of course.

**Comment by nnuss** [comment]
> Looks good, not sure how up to date those carbon-api benchmarks are.

They are almost certainly dated. When we made those comparisons the reference was 0.9.12 as I recall.

**Pull request merged**
