### PR TITLE
add architecture diagram to faq.rst

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Would you mind also backporting this to `0.9.x`?

**Comment by obfuscurity** [comment]
Restarted the failed job.

**Comment by ryan-williams** [comment]
OK. Should I do that in addition to or in lieu of sending PRs to `master`?

**Comment by obfuscurity** [comment]
Not at all. But in this case it makes sense to have it in both `master` and `0.9.x`.

**Comment by obfuscurity** [comment]
I don't know why that `TOXENV=py27-django16-pyparsing1` keeps failing due to the image but I'm probably going to merge it anyways.

**Comment by obfuscurity** [comment]
Oops, I mean `TOXENV=docs`. Hmm.

**Comment by obfuscurity** [comment]
On second thought, we need to fix whatever's breaking the docs build or it will never pass again.

@ryan-williams Check out the failed build at https://travis-ci.org/graphite-project/graphite-web/jobs/46499107 and see if you can figure out how to fix the local image issue. @gwaldo might be able to offer assistance here.

**Comment by obfuscurity** [comment]
Ok, it looks like the proper fix is to refer to the local image. Fortunately we already have it at `webapp/content/img/overview.png` so you'll just need to point to that instead. Please change this in #1092 as well.

**Comment by obfuscurity** [comment]
@ryan-williams The following patch should fix it for you. I can't test it locally because there's something broken about libcairo on the Mac.

```
diff --git a/docs/faq.rst b/docs/faq.rst
index 5150a35..1777748 100644
--- a/docs/faq.rst
+++ b/docs/faq.rst
@@ -75,7 +75,7 @@ Is there a diagram of Graphite's architecture?
 ----------------------------------------------
 There sure is! Here it is:

-.. image:: https://raw.githubusercontent.com/graphite-project/graphite-web/master/webapp/content/img/overview.png
+.. image:: ../webapp/content/img/overview.png


 .. _Django: http://www.djangoproject.com/
```

**Comment by obfuscurity** [comment]
P.S. Please update #1092 with the same change if this one passes tests.

**Comment by ryan-williams** [comment]
sorry for dropping this, applying your fix now, thanks

**Comment by obfuscurity** [comment]
Cool, thanks.

**Comment by obfuscurity** [comment]
Looks good. http://graphite.readthedocs.org/en/latest/faq.html

**Comment by ryan-williams** [comment]
hooray, thanks!

**Pull request merged**
