### PR TITLE
Have countSeries return zeroes instead of empty series

### PR DESCRIPTION
**Pull request by obfuscurity**
This supersedes #1507, bringing in @ckolbeck's enhancement and adding a test suggested by @cbowman0.

### CODE REVIEW

**Comment by obfuscurity** [comment]
Fixes #1495.

**Comment by ckolbeck** [comment]
:heart:

**Comment by 1337newbee** [comment]
@obfuscurity,
 Any idea on how I can use the latest code to implement it on my scenario? Is that in master or Graphite official website?

**Comment by obfuscurity** [comment]
@1337newbee If you're running master, just pull the latest changes and redeploy. If you're running a 0.9.x-based release you'll need to patch manually. It's a pretty small and self-contained change so it should be simple enough.

**Comment by 1337newbee** [comment]
I followed the documentation to do a step by step installation, and it was using 0.9.x.
Any idea on how to deploy it using the master? Like documentations for that?
I checked the documentation, but it's not up-to-date.

**Comment by obfuscurity** [comment]
@1337newbee Can you elaborate on what parts of the documentation are not up-to-date? The installation instructions for master should be accurate. Otherwise it's a bug and we should treat it as such.

http://graphite.readthedocs.io/en/latest/install.html

Alternatively, you can try the [Synthesize 3.0.0RC pre-releases](https://github.com/obfuscurity/synthesize/releases/tag/v3.0.0RC2) to play with or install master, or just study the [install script](https://github.com/obfuscurity/synthesize/blob/v3.0.0RC2/install) to see how it performs an installation from the master branch.

**Comment by 1337newbee** [comment]
I followed the link above and did pip install, after installation, I went to the directory and see this
drwxr-xr-x   7  staff   238 Jun 30 11:39 graphite_web-0.9.15-py2.7.egg-info
does that mean I was using 0.9.15? Or there's another place I can check the version of my Graphite?

**Comment by obfuscurity** [comment]
You didn't specify which link you're referring to. Either way if you're trying to install master then you must have done something wrong. At least with Synthesize 3.0.0RC you should see `graphite_web-0.10.0_alpha-py2.7.egg-info` in there.

**Comment by 1337newbee** [comment]
This is the link
http://graphite.readthedocs.io/en/latest/install-pip.html
and here are the commands I issue. I was using mac os
pip install https://github.com/graphite-project/ceres/tarball/master
pip install whisper
pip install carbon
pip install graphite-web

**Comment by 1337newbee** [comment]
I finally got the above one working. Validating this 
https://9.37.***.**/render?target=countSeries(currentBelow(collectd.graphite.processes.ps_state-paging,1)&format=json

It's still return [] rather than give me the desired 0.
I thought the defect above was fixed???

**Comment by obfuscurity** [comment]
No, if you're doing that then you're almost certainly installing 0.9.15. It should work if you do this instead:

```
pip install https://github.com/graphite-project/whisper/tarball/master
pip install https://github.com/graphite-project/carbon/tarball/master
pip install https://github.com/graphite-project/graphite-web/tarball/master
```

Note that you can always check your graphite-web version by visiting `http://<graphite>/version/`.

**Pull request merged**
