### PR TITLE
add verticalLine() url function

### PR DESCRIPTION
**Pull request by nharkins**
hi. i've written a verticalLine() function for graphite's url api
which draws a vertical line on the graph at a specific
timestamp specified by the first argument function, 
in the same time formats as &from= and &until=, e.g.

&target=verticalLine("12:3420131108","event","blue")

this will be handy for quickly marking ad-hoc events 
on graphs without having to think of where it belongs
in the namespace and cluttering the database.

it seems like at least one other person wanted this functionality:
https://answers.launchpad.net/graphite/+question/187677

### CODE REVIEW

**Comment by softwareklinic** [comment]
&target=verticalLine("12:3420131108","event","blue")

How did you create this number - and what does it represent   "12:3420131108"

**Comment by nharkins** [comment]
it is a timestamp, e.g. any value valid to the &from= arg
as per http://graphite.readthedocs.org/en/latest/render_api.html
"ABSOLUTE_TIME is in the format HH:MM_YYMMDD, YYYYMMDD, MM/DD/YY, or any other at(1)-compatible time format."
it seems that now an underscore is often used: HH:MI_YYYYMODD
but i seem to recall that was without it in the docs a while back, and
the old style still seems to work in my instance (backwards compat?)

i found that on the docs somewhere. looks like 
HH::MI_YYYYMODD is preferred now.

**Comment by softwareklinic** [comment]
Thank you.



Regards,
Keyur

On Oct 20, 2015, at 5:39 PM, Neil Harkins <notifications@github.com<mailto:notifications@github.com>> wrote:


it is a timestamp, e.g. any value valid to the &from= arg
as per http://graphite.readthedocs.org/en/latest/render_api.html
"ABSOLUTE_TIME is in the format HH:MM_YYMMDD, YYYYMMDD, MM/DD/YY, or any other at(1)-compatible time format."
it seems that now an underscore is often used: HH:MI_YYYYMODD
but i seem to recall that was without it in the docs a while back, and
the old style still seems to work in my instance (backwards compat?)

i found that on the docs somewhere. looks like
HH::MI_YYYYMODD is preferred now.

**Comment by obfuscurity** [comment]
@nharkins Can you rebase this so we can merge it in cleanly?

**Comment by obfuscurity** [comment]
Closing in favor of #1631.

**Pull request closed without merging**
