### PR TITLE
Make local cluster host detection configurable and disabled by default (0.9.x)

### PR DESCRIPTION
**Pull request by steve-dave**
As discussed in https://github.com/graphite-project/graphite-web/pull/1069 it seems to be preferable to make this behaviour switchable and (I think) disabled by default.

@drawks @obfuscurity @SEJeff 

0.9.x port of https://github.com/graphite-project/graphite-web/pull/1135

### CODE REVIEW

**Comment by steve-dave** [comment]
Ping @obfuscurity

**Comment by obfuscurity** [comment]
I don't have an opinion on this, deferring to @drawks and @SEJeff.

**Comment by steve-dave** [comment]
ping @drawks @SEJeff

**Comment by drawks** [comment]
patch looks fine to me, but should include a test case

**Comment by steve-dave** [comment]
Closing as I no longer have commit on the head fork. Moving to #1167

**Pull request closed without merging**
