### PR TITLE
flake8: re-enable E111,E114 (4-space indent) for most files

### PR DESCRIPTION
**Pull request by ploxiln**
The 4-space indent thing would be nice to enable checks for, but it's a huge amount of churn throughout the code-base. So my idea is to ignore this rule from the files with the most  warnings, and start working from the files with the fewest warnings.

(A reasonable alternative is to not re-enable this for flake8, and continue to let Deep Source complain about it just for functions which are modified, as we saw in #2574.)

After re-enabling the indent rules, before ignoring or fixing any files, here's the ranking of violations per file:

```
graphite-web]$ flake8 | cut -d: -f1 | uniq -c | sort -n
   1 ./webapp/graphite/url_shortener/baseconv.py
   1 ./webapp/tests/base.py
   1 ./webapp/tests/test_whitelist.py
   2 ./webapp/graphite/account/admin.py
   2 ./webapp/graphite/version/views.py
   2 ./webapp/tests/funcplugins/plugin_bad_paramtype.py
   2 ./webapp/tests/funcplugins/plugin_no_group.py
   2 ./webapp/tests/funcplugins/plugin_no_params.py
   2 ./webapp/tests/funcplugins/plugin_string_paramtype.py
   2 ./webapp/tests/test_readers_ceres.py
   2 ./webapp/tests/test_readers_multi.py
   3 ./webapp/graphite/functions/aggfuncs.py
   3 ./webapp/graphite/views.py
   3 ./webapp/tests/test_finders.py
   4 ./webapp/graphite/events/views.py
   4 ./webapp/tests/funcplugins/plugin.py
   4 ./webapp/tests/funcplugins/plugin_bad_param.py
   4 ./webapp/tests/test_readers_remote.py
   5 ./webapp/graphite/errors.py
   5 ./webapp/graphite/render/grammar.py
   5 ./webapp/tests/test_worker_pool.py
   6 ./bin/run-graphite-devel-server.py
   6 ./contrib/test_aggregator_rules.py
   6 ./setup.py
   6 ./webapp/tests/test_attime.py
   7 ./docs/conf.py
   8 ./webapp/graphite/user_util.py
   8 ./webapp/tests/test_readers_whisper.py
   9 ./webapp/graphite/logger.py
  11 ./webapp/tests/test_metrics.py
  12 ./webapp/graphite/tags/models.py
  13 ./webapp/graphite/node.py
  13 ./webapp/tests/test_util.py
  17 ./webapp/graphite/dashboard/models.py
  19 ./webapp/graphite/composer/views.py
  19 ./webapp/graphite/finders/standard.py
  19 ./webapp/graphite/readers/remote.py
  20 ./webapp/graphite/account/models.py
  20 ./webapp/graphite/account/views.py
  20 ./webapp/graphite/functions/views.py
  20 ./webapp/tests/test_render.py
  21 ./examples/example-client.py
  22 ./webapp/graphite/whitelist/views.py
  24 ./webapp/graphite/account/ldapBackend.py
  32 ./webapp/graphite/tags/http.py
  33 ./webapp/graphite/functions/__init__.py
  33 ./webapp/graphite/settings.py
  35 ./webapp/graphite/worker_pool/pool.py
  39 ./webapp/graphite/storage.py
  42 ./webapp/graphite/intervals.py
  43 ./webapp/graphite/tags/utils.py
  44 ./webapp/graphite/functions/safe.py
  44 ./webapp/graphite/render/hashing.py
  46 ./webapp/tests/test_functions.py
  47 ./check-dependencies.py
  49 ./webapp/graphite/tags/views.py
  56 ./webapp/graphite/carbonlink.py
  65 ./webapp/graphite/tags/redis.py
  68 ./webapp/graphite/render/attime.py
  71 ./webapp/graphite/tags/base.py
  76 ./webapp/tests/test_tags.py
  87 ./webapp/graphite/render/evaluator.py
 103 ./webapp/graphite/browser/views.py
 111 ./webapp/graphite/render/datalib.py
 116 ./webapp/graphite/util.py
 126 ./webapp/tests/test_storage.py
 135 ./webapp/graphite/tags/localdatabase.py
 136 ./webapp/tests/test_finders_remote.py
 142 ./webapp/graphite/dashboard/views.py
 161 ./webapp/graphite/metrics/views.py
 213 ./webapp/tests/test_render_datalib.py
 238 ./webapp/graphite/render/views.py
 261 ./contrib/memcache_whisper.py
 443 ./webapp/tests/test_render_glyph.py
 645 ./webapp/graphite/render/glyph.py
1110 ./webapp/graphite/render/functions.py
```

I'm only about one third of the way done ... please let me know whether you think this is a good idea or not :)

### CODE REVIEW

**Comment by ploxiln** [comment]
Tip: you can view only non-indent changes with: https://github.com/graphite-project/graphite-web/pull/2577/files?w=1

**Comment by ploxiln** [comment]
travis-ci is green now
please take a look @DanCech @deniszh and let me know if this is a desired path

**Comment by piotr1212** [comment]
I've compared AST's, there were 4 differences (besides a lot of whitespaces in docstrings) which I reviewed and look ok.

**Comment by ploxiln** [comment]
yeah, I threw in a couple of non-whitespace changes, which I probably should have resisted, I think these are the 4 AST changes:

```diff
 def safePow(a, b):
-  if a is None: return None
-  if b is None: return None
+    if a is None or b is None:
+        return None
     try:
```

```diff
 def functionInfo(name, func):
     argspec = inspect.getargspec(func)
+    argformat = inspect.formatargspec(argspec[0][1:], argspec[1], argspec[2], argspec[3])
     return {
         'name': name,
-    'function': name + inspect.formatargspec(argspec[0][1:], argspec[1], argspec[2], argspec[3]),
+        'function': name + argformat,
         'description': inspect.getdoc(func),
         'module': inspect.getmodule(func).__name__,
         'group': getattr(func, 'group', 'Ungrouped'),
```

```diff
     def find_series_cachekey(self, tags, requestContext=None):
         headers = [
             header + '=' + value
             for (header, value)
-      in (requestContext.get('forwardHeaders', {}) if requestContext else {}).items()
+            in (requestContext or {}).get('forwardHeaders', {}).items()
         ]
```

```diff
 class CarbonLinkPool(object):
     def __init__(self, hosts, timeout):
         self.hosts = [ (server, instance) for (server, port, instance) in hosts ]
-    self.ports = dict(
-      ((server, instance), port) for (server, port, instance) in hosts )
+        self.ports = { (server, instance): port for (server, port, instance) in hosts }
         self.timeout = float(timeout)
```

**Pull request merged**
