### PR TITLE
The SI prefix for thousands is abbreviated "k", not "K"

### PR DESCRIPTION
**Pull request by mhagger**
See, for example, [the wikipedia article](http://en.wikipedia.org/wiki/SI_prefix) referenced in [the docstring for `format_units`](https://github.com/mhagger/graphite-web/blob/df6c510b7967fea6b86cea0d85fc63121d6e4185/webapp/graphite/render/glyph.py#L1705-L1712).

### CODE REVIEW

**Comment by bmhatfield** [comment]
It's true: http://physics.nist.gov/cuu/Units/prefixes.html

Please note that you have failing tests that are looking for 'K' and now seeing 'k'. Please go through and update any/all tests that would be affected here :-)

**Comment by gwaldo** [comment]
I'm down as long as the tests are updated.

**Comment by mhagger** [comment]
Sorry about the test failure. I just fixed it.

**Comment by bmhatfield** [comment]
Looks great, thanks.

**Pull request merged**
