### PR TITLE
Add test coverage support

### PR DESCRIPTION
**Pull request by JeanFred**
- Run tests through coverage
- Get Travis-CI to upload them to CodeCov

Coverage will be computed for all test targets thanks to tox.

[See results on CodeCov](https://codecov.io/github/JeanFred/graphite-web)

(I’m usually going for Coveralls but as I quite impressed by CodeCov I thought I would give it a try. I think it’s a good pick but happy to change either way).

Later on we can look at adding some more bells and whistles like badge in ReadMe, posting on Pull Requests and so on :)

See #863

### CODE REVIEW

**Comment by obfuscurity** [comment]
Anything that adds test coverage sounds good to me but I'm pretty ignorant of Graphite's test innards. Looking for input from @SEJeff @brutasse.

**Comment by SEJeff** [comment]
I suspect seeing th coverage will just lead me to drink... More. This is totally fine by me but we are already using coveralls on whisper, so I'm not sure if we should switch them both or just use a single service.

**Comment by JeanFred** [comment]
Having it all consolidated under one service is certainly the best plan. As I said, I’m happy to change that to Coveralls.

That being said, CodeCov appears more polished & feature-complete − subjectively nicer reports ; but especially branch coverage (which is a pretty big miss from coveralls, see lemurheavy/coveralls-public#31).

**Comment by obfuscurity** [comment]
@SEJeff I defer to you and @brutasse here in matters of python testing. Please advise.

**Comment by JeanFred** [comment]
Gently upping this. :)
(I just noticed that Sentry also uses CodeCov − see eg https://github.com/getsentry/sentry/pull/2345#issuecomment-158218706)

**Comment by brutasse** [comment]
Sorry for the wait… :+1: from me!

**Comment by obfuscurity** [comment]
@JeanFred If we merge this in, can we count on you to update Carbon and Whisper to use CodeCov too?

**Comment by SEJeff** [comment]
Just remove th coveralls bits in whisper. Coveralls is a bit annoying

**Comment by JeanFred** [comment]
@obfuscurity Definitely! I’ll submit PRs to Carbon and Whisper in the coming weeks.

@SEJeff Just for clarification (we can take that further on the Whisper issue), do you want me to remove Coveralls in Whisper and replace it by CodeCov, or you’d rather not have any such tool on Whisper ?

**Comment by SEJeff** [comment]
Seems like if we like codecov, we can just switch everything to it and only it.

**Pull request merged**
