### PR TITLE
Make cacheTimeout == 0 equal to noCache being set to True

### PR DESCRIPTION
**Pull request by redbaron**

### CODE REVIEW

**Comment by deniszh** [comment]
Close/open to retrigger tests. Sometimes they're sporadically fails...

**Comment by obfuscurity** [comment]
Just fyi, we (I?) can retrigger the tests on Travis anytime.

**Comment by deniszh** [comment]
Ah, true, just find that. Thanks, @obfuscurity !

**Comment by obfuscurity** [comment]
Looked through the impact on `useCache`, seems sane. 👍

**Pull request merged**
