### PR TITLE
Graphite-web update

### PR DESCRIPTION
**Pull request by melnikk**

### CODE REVIEW

**Comment by DanCech** [comment]
@melnikk Why was this merged? Looking at the diff it doesn't do anything.

**Comment by deniszh** [comment]
It was not merged, just closed. Probably not ready yet.

**Comment by DanCech** [comment]
@deniszh ah yes, that last commit threw me for a loop.  It's not needed any more since we have `movingSum`, `movingMin` and `movingMax` now anyway.

**Comment by melnikk** [comment]
sorry, my fault, it should be a reverse merge.

**Pull request closed without merging**
