### PR TITLE
adding 'alternate storage backends' section to the tools doc

### PR DESCRIPTION
**Pull request by gwaldo**
Adding influx is not _just_ a :trollface: for @obfuscurity

### CODE REVIEW

**Comment by bmhatfield** [comment]
I'm in favor of this change. I know @obfuscurity is not a fan of all of these, but I think it's still OK and good to mention that the backends exist.

I also saw a comment where someone was using this: https://github.com/InMobi/level-tsd - is it worth including?

**Comment by obfuscurity** [comment]
It's probably fine to capitalize Ceres. Even the project README capitalizes it throughout.

**Comment by gwaldo** [comment]
I'm fine with including other backends.  This was just a list off of the few that I'd had in recent memory and seemed most-common alternates (for some value of "most").

**Comment by gwaldo** [comment]
Good point, @obfuscurity Thanks!

**Comment by deniszh** [comment]
>I also saw a comment where someone was using this: https://github.com/InMobi/level-tsd - is it worth including?

Yep, yesterday I saw question in Graphite-dev mailing list about it - it's a first time when I saw person using that. Maybe need to include to doc though...

**Comment by obfuscurity** [comment]
Going to merge this in its current state. level-tsd looks like it's not under active development and even specifies that you have to use the megacarbon branch.

**Comment by gwaldo** [comment]
Thanks!
I also backported this in https://github.com/graphite-project/graphite-web/pull/1382

**Pull request merged**
