### PR TITLE
Use POST instead of GET for find and render requests (0.9.x)

### PR DESCRIPTION
**Pull request by steve-dave**
Sometimes due to the limitations imposed by various webservers the query string generated is too long which causes cluster server requests to fail.  This patch changes requests to POST instead of GET which are not subject to those limitations.

If this patch is accepted an issue should be opened to implement the equivalent for master.  Making this change in master is slightly more complicated so I haven't done this proactively yet.

### CODE REVIEW

**Comment by steve-dave** [comment]
Now configurable :smiley:

**Comment by steve-dave** [comment]
@obfuscurity do you think it's OK to merge now?

**Comment by obfuscurity** [comment]
Instead of supplying a string value (`GET` or `POST`), I would change the setting to a boolean with a default state to `False`. This makes the conditional logic simpler as well.

```python
#REMOTE_STORE_HTTP_METHOD_POST = False # Use POST instead of GET for remote requests
```

**Comment by steve-dave** [comment]
@obfuscurity done.

**Comment by obfuscurity** [comment]
Nice. :v:

**Comment by obfuscurity** [comment]
Has this been ported to master?

**Comment by steve-dave** [comment]
Not yet.  Master is too different to allow a quick cherry-pick but I agree it needs to be done.

**Pull request merged**
