### PR TITLE
Remove pyparsing pinning requirement

### PR DESCRIPTION
**Pull request by ybizeul**
By using a Regex parser instead of building the rule we are able to get rid of the concurrency issue while loading multiple graphs.

From Paul McGuire, Pyparsing author :

> That KeyError is being raised inside the collections.OrderedDict code, and the key is extracted just a couple of lines prior to the place where the exception is raised, so we know it is a valid key. But there is a (small) window of time in which the same key could be popped by two different threads, and so the second thread will fail as the key will no longer be there.

> I've found in other parsers that building up numeric values with Combine, Word, etc. is a real slowdown compared to using a Regex, and there is not that much loss in readability or maintainability. These re's aren't that long or complicated.

### CODE REVIEW

**Comment by deniszh** [comment]
Cool! Just remove unused imports, it breaks tests.

**Comment by obfuscurity** [comment]
I haven't tested but I like the approach.

**Comment by ybizeul** [comment]
There you go!

**Comment by obfuscurity** [comment]
Would be nice to have someone benchmark reads after this change.

**Comment by iksaif** [comment]
Would be easy to write a benchmark for grammer, but I strongly suspect that grammar parsing is blazing fast compared to the I/O made when rendering the target.

**Comment by DanCech** [comment]
This looks good, but I'm not sure what the implications are of disabling packrat

**Comment by ybizeul** [comment]
Please see #1828, this becomes a real issue as pinning doesn't work in some circumstances.

**Comment by ybizeul** [comment]
@DanCech That I don't know. What I have is just words from pyparsing author that performance shouldn't be impacted. Is that your question?

**Comment by DanCech** [comment]
@ybizeul do you mean on chat or something you can link us to?

**Comment by ybizeul** [comment]
@DanCech Yes in my original post, last quote

**Comment by DanCech** [comment]
@ybizeul doesn't appear to mention packrat?

**Comment by ybizeul** [comment]
Look, I'm trying to pretend I know what we're talking about here. Obviously you got me :-D

I assumed "packrat" was the other chain parsing method, which I dropped in favor of regular expression. That's not what it is right?

**Comment by DanCech** [comment]
After reading https://pyparsing-public.wikispaces.com/Frequently%20Asked%20Questions-What%20the%20heck%20is%20%22packrat%20parsing%22? I think that as long as performance isn't affected adversely we shouldn't see any other issues from not using packrat.

**Comment by iksaif** [comment]
As said earlier, I don't think we should worry about performances here, most of the time is spent doing I/O anyway.

**Comment by deniszh** [comment]
Agreed - parsing metrics' grammar is not most heavyweight operation on graphite. But I agreed with @obfuscurity - we should benchmark that, at least on separate test.

**Comment by iksaif** [comment]
@ybizeul would you have time to write a small benchmark for that ?

**Comment by ybizeul** [comment]
@iksaif Not sure how to do that?

**Comment by iksaif** [comment]
@ybizeul I guess simply try to call grammar.parseString(target) ~10000 times with and without the patch and record the time :)

**Comment by ybizeul** [comment]
Ok, both runs with 1000 iterations.

Legacy :
```
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.total_data 2s
netapp.perf.MBP.clus1.node.clus1-01.aggr.disk_busy 3s
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.read_latency 4s
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.write_latency 4s
netapp.perf.MBP.clus1.node.clus1-01.processor.avg_processor_busy 6s
sumSeries(netapp.perf.MBP.clus1.node.clus1-01.vol_summary.total_ops) 7s
```

Patched:
```
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.read_latency 1s
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.total_data 1s
netapp.perf.MBP.clus1.node.clus1-01.vol_summary.write_latency 2s
netapp.perf.MBP.clus1.node.clus1-01.processor.avg_processor_busy 2s
sumSeries(netapp.perf.MBP.clus1.node.clus1-01.vol_summary.total_ops) 2s
netapp.perf.MBP.clus1.node.clus1-01.aggr.disk_busy 1s

**Comment by DanCech** [comment]
Very nice! Can you share the benchmarking script?

**Comment by ybizeul** [comment]
I didn't know how to isolate it, so I don't really have a script.

What I did is this in `graphite/render/evaluator.py` (and I reinstalled since then but you'll get the idea) :

```
def evaluateTarget(requestContext, target):

  sec_ = calendar.timegm(time.gmtime())

  for x in xrange(1, 1000):                                  # Loop
    tokens = grammar.parseString(target)
  result = evaluateTokens(requestContext, tokens)

  log target + " " + calendar.timegm(time.gmtime()) - sec_ # pseudo code
  if type(result) is TimeSeries:
    return [result] #we have to return a list of TimeSeries objects

  else:
    return result
```

Then just loaded a dashboard page

**Comment by deniszh** [comment]
So, is that enough to merge? @graphite-project/committers ?

**Comment by DanCech** [comment]
I think so :+1:

**Pull request merged**
