### PR TITLE
carbonlink: make it easilly importable, delay initialization

### PR DESCRIPTION
**Pull request by iksaif**
Also make readers.py pull less dependency and add
graphite.singleton to make it easier to have singleton.
This could also be used for some of our other singletons
to allow easier lazy-initialization.

See #1014 , #1886

### CODE REVIEW

**Comment by iksaif** [comment]
Also see https://github.com/criteo/biggraphite/pull/259

**Comment by iksaif** [comment]
(wait before reviews, some things apparently don't work yet)

**Comment by iksaif** [comment]
ok good now :)

**Comment by iksaif** [comment]
@deniszh : I'll probably use the same singleton.py in carbon as there are a few singleton that could benefit from it

**Comment by wdauchy** [comment]
:+1:

**Comment by deniszh** [comment]
>I'll probably use the same singleton.py in carbon too as there are a few singleton that could benefit from it

Yep, that's a good idea ! 👍 
Thanks!

**Pull request merged**
