### PR TITLE
Add Moira monitoring link

### PR DESCRIPTION
**Pull request by gmlexx**
This is new monitoring tool based on graphite data.

### CODE REVIEW

**Comment by JeanFred** [comment]
@gmlexx The [Travis build](https://travis-ci.org/graphite-project/graphite-web/jobs/99229762) failed:
`tools.rst:219: WARNING: Definition list ends without a blank line; unexpected unindent.`
Can you fix?

**Comment by deniszh** [comment]
Also, link section should be sorted alphabetically. Sorry for nit-picking. :)

**Comment by gmlexx** [comment]
I'm shocked, so much attention :)

**Comment by deniszh** [comment]
Nah, just quiet time between holidays. :)
But Moira is a nice project, indeed - thanks for adding.

**Comment by deniszh** [comment]
@JeanFred - are you gonna merge that or I ...?

**Comment by JeanFred** [comment]
Happy to merge this @deniszh − and glad you approved it, this is my very first merge in graphite after all :)

@gmlexx This is nitpicking, but can you squash your changes?

**Comment by gmlexx** [comment]
@JeanFred done!

**Comment by JeanFred** [comment]
@gmlexx And merged!

**Pull request merged**
