### PR TITLE
Make local cluster host detection configurable and disabled by default (0.9.x)

### PR DESCRIPTION
**Pull request by steve-dave**
As discussed in #1069 it seems to be preferable to make this behaviour switchable and (I think) disabled by default.

@drawks @obfuscurity @SEJeff

0.9.x port of https://github.com/graphite-project/graphite-web/pull/1166

Originally https://github.com/graphite-project/graphite-web/pull/1134

### CODE REVIEW

**Comment by steve-dave** [comment]
@drawks test added.

**Comment by steve-dave** [comment]
@drawks @bmhatfield so do we leave this as is or flip the default so that it doesn't change the current behavior?

**Comment by steve-dave** [comment]
ping @drawks @bmhatfield

**Comment by deniszh** [comment]
Hello @steve-dave,
Sorry for delay! We usually agree that default for 0.9.x should not change existing behaviour.
Could you please rebase this change? Much appreciated!

**Pull request closed without merging**
