### PR TITLE
improve efficiency of summarize and smartSummarize functions

### PR DESCRIPTION
**Pull request by DanCech**
This improves the internal efficiency of the summarize and smartSummarize functions to help improve the performance issue discussed in #1915 

As far as I can tell it should be logically identical to the existing code, but I'd appreciate any feedback.

### CODE REVIEW

**Comment by deniszh** [comment]
LGTM, but is it really gives much gain in performance?

**Comment by DanCech** [comment]
@deniszh it depends on how many data points you have, with a large number of points I was seeing about a 40% decrease in runtime compared to master which could easily be several seconds difference.

**Comment by deniszh** [comment]
@DanCech - should we merge it to master?

**Comment by DanCech** [comment]
If it looks good to you and @iksaif I don't see why not.

**Comment by deniszh** [comment]
For me it's fine 👍

**Comment by pipamc** [comment]
@DanCech Can I have your test if you feel Okey? In my compute, I can't get so high improvement.

**Comment by DanCech** [comment]
It's been a while, IIRC I was just running requests using summarize over large amounts of data from collectd and collecting timing information.

**Pull request merged**
