### PR TITLE
Add Mackerel to list of users

### PR DESCRIPTION
**Pull request by yuuki1**
Mackerel uses graphite quite heavily. I am a member of the Mackerel operation engineers.

### CODE REVIEW

**Comment by Songmu** [comment]
:+1:

**Comment by obfuscurity** [comment]
Does Mackerel base their product (hosted monitoring) on Graphite, or you're saying you use it internally to support your operations?

**Comment by Songmu** [comment]
Mackerel base the product on Graphite for displaying monitoring graphs on users dashboard. All of our time series data are stored as whisper files.

**Comment by obfuscurity** [comment]
Very cool.

**Comment by Songmu** [comment]
Thank you!

**Pull request merged**
