### PR TITLE
support 0.9.x backends

### PR DESCRIPTION
**Pull request by DanCech**
The structure of the pickled response from the find endpoints changed from 0.9.x to master, this patch allows a front-end instance running master to use back-end nodes running 0.9.x by accepting both result formats.

### CODE REVIEW

**Comment by obfuscurity** [comment]
Haven't tested but LGTM. Anyone have time to test against both backend versions?

**Comment by obfuscurity** [comment]
P.S. Great idea @DanCech. :smile_cat:

**Comment by deniszh** [comment]
Absolutely great idea, indeed!
Same here, did not tested, but looks good.
Did you tried that code, @DanCech ?

**Comment by DanCech** [comment]
@obfuscurity @deniszh yes, I've been using this code as part of the cluster performance testing so I can run both 0.9.x and master front-end nodes against the same set of 0.9.x back-end nodes to eliminate back-end node performance as a source of variation.

**Comment by DanCech** [comment]
The alternative approach would be to change the master find output to match the 0.9.x format, since I'm not sure that there's any real benefit to the change in format.

**Comment by deniszh** [comment]
I think that approach is fine. Merging.

**Pull request merged**
