### PR TITLE
Linear regression by least squares method

### PR DESCRIPTION
**Pull request by mechairoi**
Added ~~`leastSquaresForecast `~~ `linearRegression` function for graphs the liner regression by least squares method.

localhost-2

### CODE REVIEW

**Comment by yuuki1** [comment]
:+1:

**Comment by shoichimasuhara1982** [comment]
:+1:

**Comment by JeanFred** [comment]
Would you able to provide a test for that new method?

**Comment by mechairoi** [comment]
@JeanFred Thank you for the advice. I have wrote a test.

**Comment by Songmu** [comment]
@JeanFred Thank you for the review.

We heavily use graphite in our monitoring SaaS [Mackerel](https://mackerel.io) for two years. @mechairoi he is in out team.

This feature is very useful for us (and all users, of cource).

We hope this pull request to be accepted.

**Comment by JeanFred** [comment]
Thanks for writing this test @mechairoi!
This looks fine to me, but as a recent maintainer I would much prefer someone else has a look to it (poke @obfuscurity ?)

**Comment by obfuscurity** [comment]
This is probably a dumb question, but does it make sense to default `startSourceAt` to the `from` parameter?

**Comment by mechairoi** [comment]
These arguments  are copied from the `timeSlice` function, but it sounds great.

Does it also make sense to default `endSourceAt` to the `until` as follows?

```diff
--- a/webapp/graphite/render/functions.py
+++ b/webapp/graphite/render/functions.py
@@ -2389,7 +2389,7 @@ def linearRegressionAnalysis(series):
     offset = (sumII * sumV - sumIV * sumI) /denominator - factor * series.start
     return factor, offset
 
-def linearRegression(requestContext, seriesList, startSourceAt, endSourceAt="now"):
+def linearRegression(requestContext, seriesList, startSourceAt=None, endSourceAt=None):
   """
   Graphs the liner regression function by least squares method.
 
@@ -2407,8 +2407,8 @@ def linearRegression(requestContext, seriesList, startSourceAt, endSourceAt="now
   """
   results = []
   sourceContext = requestContext.copy()
-  sourceContext['startTime'] = parseATTime(startSourceAt)
-  sourceContext['endTime'] = parseATTime(endSourceAt)
+  if startSourceAt is not None: sourceContext['startTime'] = parseATTime(startSourceAt)
+  if endSourceAt is not None: sourceContext['endTime'] = parseATTime(endSourceAt)
```

**Comment by mechairoi** [comment]
@obfuscurity Thank you for the review. I fixed default `startSourceAt` and `endSourceAt`. Please let me know if you have any concerns.

**Comment by Songmu** [comment]
@obfuscurity @JeanFred 
How about it?

**Comment by JeanFred** [comment]
@Songmu Looks good to me ; but still too junior to press the merge button :)

**Comment by brutasse** [comment]
@JeanFred do it :)

**Comment by JeanFred** [comment]
All right, let’s do this then :) @mechairoi, would you be able to squash this?

**Comment by mechairoi** [comment]
@JeanFred  squashed :)

**Comment by JeanFred** [comment]
Aaaaaaand done!

**Comment by Songmu** [comment]
:smile:

**Pull request merged**
