### PR TITLE
0.9.16 release docs

### PR DESCRIPTION
**Pull request by deniszh**
Also, contains 1.0.0 release. Let's discuss and fix all issues here, I'll port that to master.

### CODE REVIEW

**Comment by deniszh** [comment]
Current issues (TODO):
1. Ceres deprecation (if needed) in master
2. Add whisper changes in master

**Comment by iksaif** [comment]
Cool, thanks for working on it

**Comment by deniszh** [comment]
OK, I fixed issues here.
Let's pick a date for release, fix date here, cherry-pick this to 1.0.0 and master and finally make a release!
@iksaif @DanCech @obfuscurity

**Comment by iksaif** [comment]
> Let's pick a date for release, fix date here, cherry-pick this to 1.0.0 and master and finally make a release!

I guess early next week would work if we can finishing everything in the 1.0.0 milestone.

**Comment by deniszh** [comment]
We can insert date later, of course. But pick one and make it on-time is more exciting. :)
I'm fine with both variants. Will port that to master change today.

**Pull request merged**
