### PR TITLE
Remove Twisted dependency (0.9.x)

### PR DESCRIPTION
**Pull request by obfuscurity**
We continue to trip over mismatched Twisted dependencies in our requirements (vs Carbon). Considering that Twisted **isn't even needed** for graphite-web, it seems stupid to keep this intact. Testing this against 0.9.x for now.

### CODE REVIEW

**Comment by deniszh** [comment]
:+1:

**Comment by obfuscurity** [comment]
Just FYI, a little more background on why I started down this path. I've been testing 0.9.x in Synthesize and recently started seeing the following exception when starting or stopping Carbon. I can't find any evidence that this is a regression caused by recent versions of Twisted **or** by the existence of different Twisted versions on the same host, but it goes away for me when we remove the Twisted requirement for graphite-web.

```
Stopping carbon-cache-1: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 382, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 508, in opt_reactor
    installReactor(shortName)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/reactors.py", line 79, in installReactor
    for installer in getReactorTypes():
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 464, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugins/twisted_core.py", line 5, in <module>
    from twisted.internet.endpoints import _SystemdParser, _TCP6ServerParser, _StandardIOParser
exceptions.ImportError: cannot import name _SystemdParser
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 595, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 226, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 607, in subCommands
    for plug in plugins:
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 464, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/local/lib/python2.7/dist-packages/twisted/plugins/twisted_core.py", line 5, in <module>
    from twisted.internet.endpoints import _SystemdParser, _TCP6ServerParser, _StandardIOParser
exceptions.ImportError: cannot import name _SystemdParser

```

**Comment by deniszh** [comment]
Just hit the same thing, testing my PRs on Synthesize. :)

**Comment by obfuscurity** [comment]
@deniszh Try the following patch to test this PR, works for me.

```
$ GRAPHITE_RELEASE=0.9.x vagrant up
```

```
diff --git a/install b/install
index f1af04d..46102f9 100755
--- a/install
+++ b/install
@@ -30,7 +30,8 @@ RUNLEVEL=1 apt-get install -y libcairo2-dev libffi-dev pkg-config python-dev pyt

 # Download source repositories for Graphite/Carbon/Whisper and Statsite
 cd /usr/local/src
-git clone https://github.com/graphite-project/graphite-web.git
+#git clone https://github.com/graphite-project/graphite-web.git
+git clone https://github.com/obfuscurity/graphite-web.git
 git clone https://github.com/graphite-project/carbon.git
 git clone https://github.com/graphite-project/whisper.git
 git clone https://github.com/armon/statsite.git
@@ -38,7 +39,8 @@ git clone https://github.com/armon/statsite.git
 # Build and install Graphite/Carbon/Whisper and Statsite
 cd whisper; git checkout ${GRAPHITE_RELEASE}; python setup.py install
 cd ../carbon; git checkout ${GRAPHITE_RELEASE}; pip install -r requirements.txt; python setup.py install
-cd ../graphite-web; git checkout ${GRAPHITE_RELEASE}; pip install -r requirements.txt; python check-dependencies.py; python setup.py install
+#cd ../graphite-web; git checkout ${GRAPHITE_RELEASE}; pip install -r requirements.txt; python check-dependencies.py; python setup.py install
+cd ../graphite-web; git checkout fix/remove_twisted_dependency; pip install -r requirements.txt; python check-dependencies.py; python setup.py install
 cd ../statsite; pip install --egg SCons; make; cp statsite /usr/local/sbin/; cp sinks/graphite.py /usr/local/sbin/statsite-sink-graphite.py

 # Install configuration files for Graphite/Carbon and Apache
```

**Comment by deniszh** [comment]
Works now, thanks!

**Comment by obfuscurity** [comment]
@deniszh Any last-minute objections before I merge this?

**Comment by brutasse** [comment]
zope-interface isn't needed by graphite-web either :)

**Comment by deniszh** [comment]
Not from my side, LGTM!
[LGTM](http://lgtm.in/i/qJsNarnCn)

**Comment by deniszh** [comment]
Yay, @brutasse is right.

**Comment by obfuscurity** [comment]
Good catch, thanks @brutasse.

**Pull request merged**
