### PR TITLE
[1.1.x] Merge prefetched data. (#2507) | Fix AttributeError if parameter validation fails (#2510) | Taming lint (#2512) | relax enforcement of options sets in validation (#2513) | introduce paramtype for agg or series func (#2523) | add new

### LINKED ISSUE #2541: [BUG] Parameter `total` of function `asPercent()` has a wrong type defined
**Describe the bug**
Under certain circumstances the parameter `total` of the function `asPercent()` may have different types, depending on other specified parameters. But the type assigned with this parameter is always `seriesList`, this isn't always correct: https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L871
This may cause the input validation to incorrectly consider a the given value invalid

**To Reproduce**
Enforce input validation and use the `asPercent()` function with a numeric value as `total`

**Expected behavior**
This should be considered valid

**Additional context**
I'll make a PR to fix it

### PR DESCRIPTION
**Pull request by deniszh**
Backports the following commits to 1.1.x:
 - Merge prefetched data. (#2507)
 - Fix AttributeError if parameter validation fails (#2510)
 - Taming lint (#2512)
 - relax enforcement of options sets in validation (#2513)
 - introduce paramtype for agg or series func (#2523)
 - add newline (#2525)
 - convert keys to string before sorting (#2525)
 - explicitely mark each function that can be used as aggregator (#2528)
 - add test (#2528)
 - Python 3.9 support: remove deprecated U option to open (#2529)
 - remove leading ~ from name when indexing metric names (#2458)
 - remove leading ~ from name when indexing metric names (#2458)
 - add graphite-dl4j and carbon-proxy (#2521)
 - Trying to fix tests (#2530)
 - simplify travis-ci config (#2532)
 - test docs on Python3 (#2535)
 - Django 3.0 compatibility (#2534)
 - fix function parameter types (#2536)
 - Parameter type int or inf (#2538)
 - interpret inf as unquoted value (#2539)
 - add inf to evaluator test (#2539)
 - fixes #2541 (#2542)
 - fix test (#2542)
 - better error messages (#2543)

### CODE REVIEW

**Comment by deniszh** [comment]
Preparing 1.1.7 release

**Comment by piotr1212** [comment]
2458 is listed twice

**Comment by deniszh** [comment]
Yes, that's how backport works with squashed commits. For some reason it still sees individual commits, but they are empty.

That's why I want to implement something else, like `backportbot` github action.

**Comment by deniszh** [comment]
I mean, PR is good, despite duping

**Pull request merged**
