### PR TITLE
Render infinite values to valid JSON values. Fixes #813

### LINKED ISSUE #813: json with `Infinity` values is invalid
When I make a request like `http://mygraphite.com/render/?target=some.metric.name&format=json`, I expect to get valid JSON.

I sometimes get invalid JSON containing `Infinity` values.

``` json
[{"target": "some.metric.name", "datapoints": [[Infinity, 1407296460], [Infinity, 1407296520], [Infinity, 1407296580]]}]
```

Not sure what the correct output should be. Maybe `null`?

### PR DESCRIPTION
**Pull request by rehevkor5**
- The 'json' and 'jsonp' formats output float('inf') as 1e9999, float
  ('-inf') as -1e9999, and float('nan') as null
- The 'dygraph' format (a JSON-based format) outputs the same as
  Infinity, -Infinity, and null (see http://dygraphs.com/tests/gviz-infinity.html)
- Minor updates to documents to make sure commands can be run without errors or problems

### CODE REVIEW

**Comment by rehevkor5** [comment]
Disclaimer: I am not really a Python developer, so hopefully I didn't do anything terribly thickheaded.

**Comment by deniszh** [comment]
LGTM.
I would prefer separate commits for docs and functionality itself, but maybe I'm nitpicking here.
Any other reviewers? /cc @graphite-project/committers ?

**Comment by obfuscurity** [comment]
@torkelo Would this cause any problems for Grafana?

**Comment by torkelo** [comment]
No,  I think this is an improvement, if I recall correctly the Infinite value returned by graphite today cause invalid json errors

**Comment by obfuscurity** [comment]
Note that I want to merge this in but not until #1690 is resolved. There is a related branch that's already pretty complicated that I'd like to see go in first, then we can rebase this one.

**Comment by rehevkor5** [comment]
@obfuscurity regarding your question about whether this might cause problems for Grafana: I created this PR in order to resolve problems with Grafana, actually! I have seen graphs refuse to render if `Infinity` is in the JSON returned by Graphite.

**Comment by obfuscurity** [comment]
Going to merge this now. Discussed with @DanCech, he said he'd rebase this into his ongoing work related to #1690.

**Pull request merged**
