### PR TITLE
List Promitor as a collector tool

### PR DESCRIPTION
**Pull request by tomkerkhove**
Relates to https://github.com/tomkerkhove/promitor/issues/938

### CODE REVIEW

**Comment by deniszh** [comment]
Ok, it's a bit stretched here, but fine, I think.

**Comment by tomkerkhove** [comment]
Thanks for merging!

Just wondering, what do you mean with a bit stretched? The text or? Otherwise I'm happy to adapt.

**Comment by deniszh** [comment]
No worries, I meant that it has support of statsd and not Graphite directly. But I'm just nitpicking. :P

**Comment by tomkerkhove** [comment]
Oh you have a point - Sorry!

**Pull request merged**
