### PR TITLE
aliasByNode(): support all allowed chars

### PR DESCRIPTION
**Pull request by iksaif**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Can you add any tests for this?

**Comment by iksaif** [comment]
Done, also re-wrote the thing using grammar.

**Comment by obfuscurity** [comment]
Very nice change. I forgot grammar was even there. 😄 

LGTM. 👍

**Comment by iksaif** [comment]
could somebody with complex aliasByNode queries validate that it works before I merge it ? :)

**Comment by iksaif** [comment]
let's merge and see

**Comment by biancalana** [comment]
Does this commit fix metric containing '@' ?

**Pull request merged**
