### PR TITLE
Replace charged language "whitelist/blacklist"

### PR DESCRIPTION
**Pull request by gwaldo**
Addressing https://github.com/graphite-project/graphite-web/issues/1569

Related to https://github.com/graphite-project/carbon/issues/567 / https://github.com/graphite-project/carbon/pull/568

**EDIT:** This isn't tested, but is ready for review.

### CODE REVIEW

**Comment by gwaldo** [comment]
I haven't had a chance to test, but I think that this is all of the edits that I need to make.  @graphite-project/committers please have a look.

**Comment by cbowman0** [comment]
@gwaldo can you rebase from master?  I can help resolve any issues with the unit tests after that, unless you wish to do them yourself.

**Comment by obfuscurity** [comment]
@gwaldo Got time to rebase?

**Comment by obfuscurity** [comment]
@gwaldo Do you have time to continue work on this? If not I can pick it up from you, just let me know.

**Comment by gwaldo** [comment]
I haven't had time/energy to work on this, so yes, @obfuscurity (per our chat), I would be perfectly happy if you would be able to finish it.

**Comment by obfuscurity** [comment]
Closing in favor of #1700.

**Pull request closed without merging**
