### PR TITLE
Applying #1560 fix to python 2.6 as well

### PR DESCRIPTION
**Pull request by roeezab**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Did you test this against Python 2.7?

**Comment by roeezab** [comment]
No. I tried adjusting my environment to test it but having trouble with it :/

**Comment by obfuscurity** [comment]
Ok, just an FYI that we won't merge this until it's been tested for regressions.

**Comment by roeezab** [comment]
ok thanks, I'll keep working on it.

**Comment by obfuscurity** [comment]
Tested this with Python 2.7 on Graphite 0.9.15 (Synthesize). No visible regressions.

**Pull request merged**
