### PR TITLE
Apply hashing to remote storage cache key

### PR DESCRIPTION
**Pull request by bitprophet**
Prevents hitting the memcache 250-char key limit when rendering very long metric paths in cluster setups.

This looks like it regressed in f18bb3c7 and since that looks like a squashed merge I can't tell why it was changed during the megacarbon work; presumably it was to update the data used to construct the key. Either way, this change doesn't modify the nature of the key, only ensures it is hashed like all other memcached-using code (eg in `render/views.py`).

### CODE REVIEW

**Comment by drax68** [comment]
+1 Hit this issue too. Any chance that this will be merged soon?

**Comment by bitprophet** [comment]
Given I barely contribute, I'd like to merge this but would :heart: a simple :+1: from any other @graphite-project/committers first to make sure I'm not committing a faux pas. An emoji will do! A day or two of silence may be taken as consent :)

**Comment by JeanFred** [comment]
@bitprophet The rationale sounds sensible to me, and the code looks fine − but I’m not familiar enough with the codebase in general for even an emoji on this :-)

**Comment by JeanFred** [comment]
Wait, looks like #1480 is the same as this? (Good news is that @deniszh +1 it ;-)

**Comment by obfuscurity** [comment]
I prefer the bit savings in #1480 but the logic seems ok either way.

**Comment by deniszh** [comment]
Yep, or this or #1480 - both looks fine. Pick one, ditch another, merge. 👍

**Comment by obfuscurity** [comment]
Merged #1480.

**Pull request closed without merging**
