### PR TITLE
 - added avg_zero support for consolidate function

### PR DESCRIPTION
**Pull request by eachirei**
https://github.com/graphite-project/graphite-web/issues/2337

### CODE REVIEW

**Comment by piotr1212** [comment]
lgtm, Could you please add it to the tests? somewhere here https://github.com/graphite-project/graphite-web/blob/master/webapp/tests/test_functions.py#L1443-L1449

**Comment by deniszh** [comment]
Thanks, @eachirei !
But please add tests, as @piotr1212 said.

**Comment by eachirei** [comment]
Done! Not sure if I should add one of these as well: https://github.com/graphite-project/graphite-web/blob/824800a4218c8cb9ab56ca67277b0f7774a7ff1d/webapp/tests/test_readers_util.py#L179-L210

**Comment by DanCech** [comment]
This looks good, we should add `avg_zero` to the `consolidateBy` function docs and also add it to `aggFuncs` in `functions.py` so that it can be used consistently throughout the system.

**Comment by DanCech** [comment]
On further review, this only adds support for `merge_with_cache` consolidation at read time for whisper files using `avg_zero` consolidation.

To support `avg_zero` in `consolidateBy` it would need to be added to `__consolidatingGenerator` in `TimeSeries` which will take some effort as that is geared entirely toward discarding `None` values.  The test passes because it just verifies that `series.consolidationFunc` is set, not that it actually functions.

To support `avg_zero` in functions that perform consolidation is possible, and doesn't require too much work.

At this point I'd accept this as a bugfix if the change in `webapp/tests/test_functions.py` is removed, then support for `avg_zero` in `consolidateBy` and the aggregation functions could be added separately.

**Comment by deniszh** [comment]
Superceded by https://github.com/graphite-project/graphite-web/pull/2380

**Pull request closed without merging**
