### PR TITLE
fix for issue 2012

### PR DESCRIPTION
**Pull request by leochen4891**
to fix https://github.com/graphite-project/graphite-web/issues/2012
remove file extension when getting `base_fs_path `
use `os.sep` to replace `'/'`
rename 
  `real_fs_path `to `real_aboslute_path`
  `relative_real_fs_path  `to `real_relative_fs_path `

### CODE REVIEW

**Comment by leochen4891** [comment]
Use @zasca's example

```
>>> absolute_path='/var/lib/graphite/whisper/Env/HTTP/NumConnections.wsp'
>>> metric_path='Env.HTTP.NumConnections'
>>> real_absolute_path='/mnt/ssd/graphite/db/Env/HTTP/NumConnections.wsp'
>>> 
>>> relative_fs_path = metric_path.replace('.', os.sep)
>>> print relative_fs_path
Env/HTTP/NumConnections
>>>
>>> absolute_path_no_ext, _ext = os.path.splitext(absolute_path)
>>> print absolute_path_no_ext
/var/lib/graphite/whisper/Env/HTTP/NumConnections
>>> 
>>> base_fs_path = os.path.dirname(absolute_path_no_ext[:-len(relative_fs_path)])
>>> print base_fs_path
/var/lib/graphite/whisper
>>> 
>>> real_base_fs_path="/mnt/ssd/graphite/db/"
>>> 
>>> real_absolute_path[len(real_base_fs_path):]
'Env/HTTP/NumConnections.wsp'
>>> 
>>> real_relative_fs_path = real_absolute_path[len(real_base_fs_path):].lstrip(os.sep)
>>> print real_relative_fs_path
Env/HTTP/NumConnections.wsp
>>> 
>>> fs_to_metric(real_relative_fs_path)
'Env.HTTP.NumConnections'
```

**Comment by iksaif** [comment]
would be great to add an associated unit test to clearly show that this fixes.

**Comment by leochen4891** [comment]
unit test added.
without the fix, the test will fail with
`AssertionError: 'HTTP.NumConnections' != 'Env.HTTP.NumConnections'`

**Comment by deniszh** [comment]
Thanks, LGTM.
More reviews? /cc @DanCech @iksaif ?

**Comment by cbowman0** [comment]
This appears to function properly.

Can you add a test case for when the symlink is inside of the metric path as opposed to the base path itself: `/opt/graphite/storage/whisper/foo/bar` is a symlink to `/opt/graphite/storage/whisper/baz/`
`get_real_metric_path` function should return `baz.blah`.

**Comment by leochen4891** [comment]
@cbowman0 
Good point to cover the case that the symbolic link is inside the metric path.
Test case added.

**Pull request merged**
