### PR TITLE
Prepend REMOTE_STORE_METRIC_PREFIX to all metrics queried…

### PR DESCRIPTION
**Pull request by jstangroome**
… from upstream Graphite-Web instances. Refs #1268.

### CODE REVIEW

**Comment by jstangroome** [comment]
CI needs to be re-run following merge of PR #1273

**Comment by obfuscurity** [comment]
Seems like an idea worth of inclusion to 0.9.x, but would you mind adding it to local_settings.py.example with some comments or documentation?

**Comment by deniszh** [comment]
Hello @jstangroome,
Could you please include some documentation for this feature, e.g. from https://github.com/graphite-project/graphite-web/issues/1268 ?

**Comment by DanCech** [comment]
@deniszh at this point wouldn't we be adding this to master rather than 0.9.x?

**Comment by deniszh** [comment]
@DanCech - if @jstangroome still interested in this feature we can port it to master too.
But I just found out that this thing separates only whisper dirs, with disabled Carbonlink. Not sure if viable solution...

**Comment by jstangroome** [comment]
@DanCech @deniszh We are using this feature in Production very effectively and would like to see it become part of Graphite proper.

I am happy to contribute documentation. Do you feel there is a particular documentation page where this should be added, or should a new page be introduced?

The solution is working with Carbonlink in our deployment, which is as follows:

1. User-Agent requests `graphite/render/?target=some.metric` from Front End Graphite (aka `FEG`)
1. `FEG` is configured with `REMOTE_STORE_METRIC_PREFIX="customer1."` and `CLUSTER_SERVERS=["BEG1:8080", "BEG2:8080"]` where `BEG1` and `BEG2` are Back End Graphite instances.
1. `FEG` prepends `customer1.` to the beginning of `target`, forming `customer1.some.metric` then requests `customer1.some.metric` from `BEG1` and `BEG2`.
1. `BEG1` and `BEG2` do *not* have `REMOTE_STORE_METRIC_PREFIX` defined but *do* have `WHISPER_DIR = '/opt/graphite/storage/whisper'` and `CARBONLINK_HOSTS = ['127.0.0.1:7002']`.
1. `BEG*` both check the disk for `/opt/graphite/storage/whisper/customer1/some/metric.wsp` and query Carbon Cache for `dict(type='cache-query', metric='customer1.some.metric')` and has been confirmed with `tcpdump port 7002`.
1. `BEG*` return all matching data for `customer1.some.metric` to `FEG`.
1. `FEG` strips the `customer1.` prefix from the matching metric paths before returning the result to the User-Agent.

@DanCech is correct that `REMOTE_STORE_METRIC_PREFIX` does not work with Carbonlink when the architecture is reduced to fewer layers (ie User-Agent -> Graphite -> disk,Carbon-Cache) but maybe this is solvable with changes to `carbonlink.py`. It took me some time to grok the code-base just for my scenario so I didn't attempt to go further.

Perhaps documenting the current limitation with respect to Carbonlink in simpler architectures would be sufficient to allow this to be merged? Supporting Carbonlink fully could maybe wait until this capability is requested.

**Comment by deniszh** [comment]
Thanks for explanation, @jstangroome !
IMO that's a nice feature to have. But we have 2 issues:
1) Lack of documentation. I think you need to add your explanation how it works and warning for indirect Carbonlnk support. You can add new page under https://graphite.readthedocs.io/en/latest/config-webapp.html and add link from [local_settings.py explanation](https://graphite.readthedocs.io/en/latest/config-local-settings.html)
2) We can add this feature to 0.9.x, but it will be abandoned very soon, and next version (1.0.0) will be derived from master very soon. So, if you want to make it part of Graphite you need to port it to `master` branch. Is that OK?

**Comment by jstangroome** [comment]
@deniszh I couldn't find the mentioned documentation file in the 0.9.x branch so I used `docs/config-local-settings.rst` instead. I hope that's ok.

I will investigate what is required to port this feature to the master branch but I would appreciate if it can be merged into 0.9.x until then.

**Comment by deniszh** [comment]
I'm 👍 for merging this if no objections.

@DanCech @iksaif @obfuscurity  - how do you feel about final 0.9.16 release, together with 1.0.0?
It will address some nasty bugs in 0.9.15, like https://github.com/graphite-project/graphite-web/issues/1868 and couple of others.
Of course, we should mention that upgrade to 1.0.0 is encouraged, and you shouldn't use 0.9.16 until you have some serious reason to do so, like legacy OS, python etc.

@jstangroome: Thank you for your contribution, but please do not forget to port that change to master, otherwise, it will be gone soon.

**Comment by DanCech** [comment]
At first glance it appears that the way the prefix add/remove code is structured is too permissive, and would cause problems if a user defined a metric that happened to start with the same node(s) as the prefix.

**Comment by DanCech** [comment]
In my opinion, if we're going to support a setting like this it needs to be enforced properly, with the prefix being added to every request and any results returned from the remote node that don't start with the prefix discarded.

**Comment by jstangroome** [comment]
@DanCech Good points.

Continuing my example above, an end-user request for `?target=customer1.some.metric` would propagate to the back-end unaltered but upon return would be presented as just `some.metric`.

Similarly if there was a back-end metric named `customer1.customer1.foo` then the end-user would need to request `?target=customer1.customer1.foo` to access it and upon return it would be presented as just `customer1.foo`.

This behaviour is certainly suboptimal but should still mean that all metrics returned from the back-end are constrained to the subset defined by the prefix configuration even if the returned names don't match the requested names.

To be honest, the original commit for this PR was written so long ago that I don't recall if it was necessary for the prefix to be conditionally prepended and truncated or if it was just because I was uncertain about the how the original code would call my code.

I'll take a stricter approach when I implement this for master. Do you need a stricter approach before merging this PR for 0.9.x?

**Comment by DanCech** [comment]
Closing this, if we want to pursue it we'll need to rebase onto master

**Pull request closed without merging**
