### PR TITLE
Enable advanced alignment for smartSummarize

### PR DESCRIPTION
**Pull request by luigiberrettini**
I modified smartSummarize and the related tests to allow an alignment indipendent from the interval that could be set to:
 - seconds
 - minutes
 - hours
 - days
 - weeks (starting from a specified day of the week)
 - months
 - years

### CODE REVIEW

**Comment by deniszh** [comment]
I'm 😐 about this change - but weeks with some specified dow could be useful. @luigiberrettini - could you please clean up white spaces in lines below? Lint is complaining - 

`/home/travis/build/graphite-project/graphite-web/webapp/graphite/render/attime.py:165:50: W292 no newline at end of file`
`/home/travis/build/graphite-project/graphite-web/webapp/graphite/render/functions.py:3725:1: W293 blank line contains whitespace`

Thanks a lot!

**Comment by luigiberrettini** [comment]
I did not change the `test_render_view` failing in Travis CI and it seems not to depend on smartSummarize
It is failing after changing another test: this is a non-sense

**Comment by deniszh** [comment]
@luigiberrettini - yes, looks like flaky test. It's green now.
Maybe someone else wants to look? @DanCech @iksaif ?

**Comment by iksaif** [comment]
LGTM

**Pull request merged**
