### PR TITLE
Add test coverage to /metrics/

### PR DESCRIPTION
**Pull request by cbowman0**
I am attempting to understand how to create test cases in Graphite.  This adds coverage to graphite.metrics.

### CODE REVIEW

**Comment by deniszh** [comment]
Same here. :+1:
Need to do the same, maybe will learn that too from your code. Much appreciated!

**Comment by cbowman0** [comment]
I have something going for this, but to really test the edge cases more will be necessary.

Also, some views in graphite.metrics don't seem to work with Django 1.9.  I'll be pushing a fix after I transfer trains.

**Comment by JeanFred** [comment]
Same as others − very much appreciate all this work! Will try to have a look later :)

**Comment by cbowman0** [comment]
*grumble* returned json isn't sorted.

**Comment by cbowman0** [comment]
I think this is as far as I'm going to get for now.  I'm ready to merge after someone else has had a chance to look over it.

There's a few cases (get/set metadata) where I don't know how to invoke a valid request.  I have deduced a valid key from a short amount of digging.

Overall, I think I have covered the majority of the requests variations, but that's where the coverage may be lacking so if someone sees something that was missed let me know.

**Comment by obfuscurity** [comment]
:heart:

**Pull request merged**
