### PR TITLE
Fixed misleading doc for function diffSeries

### PR DESCRIPTION
**Pull request by g76r**
Constants are not supported.
See issues #626 and #415 that assume not supporting constants is a bug.

### CODE REVIEW

**Comment by SEJeff** [comment]
Would you mind adding a blurb about using offset() to do what people obviously assume they should be able to do with diffSeries please?

**Comment by g76r** [comment]
@SEJeff done.

**Comment by SEJeff** [comment]
Any chance you'd mind doing this in 0.9.x as well so it makes it into 0.9.13, our last 0.9.x releases?

**Comment by g76r** [comment]
@SEJeff  Done. #1108

**Comment by g76r** [comment]
BTW I wonder how one can still use 0.9.x, I switched to master-in-production for a while ;-)

**Comment by SEJeff** [comment]
I wish more of our users were like you :)

As @mleinart slowly merges the megacarbon bits back into master, it is going to be shaping up into a very nice thing indeed

**Pull request merged**
