### PR TITLE
Fix install documentation for pip packages

### LINKED ISSUE #1079: pip package doesn't honor requirements.txt
Similar to https://github.com/graphite-project/carbon/issues/348.

### PR DESCRIPTION
**Pull request by obfuscurity**
Fixes #1079 and https://github.com/graphite-project/carbon/issues/348.

### CODE REVIEW

**Comment by obfuscurity** [comment]
The cairocffi and libffi bits should also be ported to master if this looks :+1: but I wanted to get peer review first.

**Comment by deniszh** [comment]
Just tested manual on fresh Ubuntu 12.04 and 14.04 VMs, looks good! :+1: 
BTW, requirements.txt for graphite-web in 0.9.x contains 
```
git+git://github.com/graphite-project/whisper.git@0.9.x#egg=whisper
```
Do we need to change it to
```
git+git://github.com/graphite-project/whisper.git@0.9.13#egg=whisper
```
later?

**Comment by obfuscurity** [comment]
Yeah, I guess it wouldn't hurt to change that to `0.9.13` now since we're not planning to do any more `0.9.x` releases.

**Pull request merged**
