### PR TITLE
Implement __eq__ for TimeSeries.

### PR DESCRIPTION
**Pull request by cbowman0**
Without this testing equality of two TimeSeries will compare the list contents but not the private variables

Potential fix for #1589.

### CODE REVIEW

**Comment by cbowman0** [comment]
Rebased against master.

I fixed the failing unit tests and cleaned up some more that were doing extra or useless tests now that there is an equality operator for TimeSeries.

**Comment by cbowman0** [comment]
I believe this is ready to go.

**Comment by obfuscurity** [comment]
Ok with me if it's ok with @SEJeff.

**Comment by SEJeff** [comment]
Yup, I love how much crud this cleans up in the tests.

**Pull request merged**
