### PR TITLE
Fix braces expander

### PR DESCRIPTION
**Pull request by unitmatrix**

### CODE REVIEW

**Comment by unitmatrix** [comment]
The "curly braces expansion" bug from v0.9.16 affects most rhel7/centos7 machines that have graphite installed from the epel repo which provides graphite-web-0.9.16 as the latest at the moment (https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/graphite-web-0.9.16-3.el7.noarch.rpm)

**Comment by deniszh** [comment]
Hi @unitmatrix ,

Sure, we can merge it, but please note that 0.9.x branch is unmaintained, 0.9.16 was last release in 0.9.x and we're not going to make new releases there - https://github.com/graphite-project/graphite-web/compare/0.9.16...0.9.x
EPEL package maintainers can release fixed version, of course.

**Review by deniszh — APPROVED** [review]

**Comment by deniszh** [comment]
Ah, @piotr1212 - are you maintainer of EPEL package? I see https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-c7b042b501

**Comment by deniszh** [comment]
Will merge 0.9.x patch, I'm doubt if it worth to make tests there

**Pull request merged**
