### PR TITLE
Fix get_real_metric_path for paths where an intermediate directory is a symlink

### PR DESCRIPTION
**Pull request by yadsirhc**
See #2320

### CODE REVIEW

**Comment by deniszh** [comment]
Well, change looks good, but something is happening with Travis CI integration.

**Comment by yadsirhc** [comment]
Any ideas on why Travis CI is flagging it as "Abuse detected"?

**Comment by deniszh** [comment]
Where did you see that, @yadsirhc ?

**Comment by yadsirhc** [comment]
@deniszh Should I try closing this PR and opening a new one?  My gut tells me that the initial PR for the change followed later by adding the unit test may be why it was rejected by Travis CI.

**Comment by deniszh** [comment]
Yes, please try that. Thanks!

**Pull request closed without merging**
