### PR TITLE
Add timeshift test coverage

### PR DESCRIPTION
**Pull request by cbowman0**

### CODE REVIEW

**Comment by DanCech** [comment]
Any reason not to use mock?

**Comment by cbowman0** [comment]
For `functions.evaluateTarget`?

**Comment by DanCech** [comment]
Yeah, I see that there are a few places in `test_functions.py` with the manual patching, and other places that use `with patch('graphite.render.evaluator.fetchData', mock_data_fetcher):` for scenarios like this.

**Comment by cbowman0** [comment]
Right.  I used the manual patching to keep with the other methods.  Mock makes more sense.  I'll rework this and the other cases that were similar to mock `fetchData`.

**Pull request merged**
