### PR TITLE
average/current/max/min Above/Below fails if there is no data.

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
- Adds check for None before integer comparisons.
- Converts list comprehension code into loop.
- Add tests for averageAbove/Below()
- Add tests for currentAbove/Below()
- Add tests for maximumAbove/Below()
- Add tests for minimumAbove/Below()

N.B: These functions only fail when using Python 3, not 2.7.

### CODE REVIEW

**Comment by deniszh** [comment]
Running tests on python3 and app itself on 2.7... ?

**Comment by iain-buclaw-sociomantic** [comment]
Hmm, I didn't check to see that there are already a test for all `None` series.  I guess I should tweak the behaviour then.

@deniszh - Running graphite-api, but the same problem is present here also.

**Comment by iksaif** [comment]
any news ?

**Comment by obfuscurity** [comment]
LGTM 👍

**Pull request merged**
