### PR TITLE
added  new parameter to json format [ jsondpfmt = "XmsY" ] 

### PR DESCRIPTION
**Pull request by toni-moreno**
added jsondpfmt (datapoint format) to  XmsY to json format allowing client side apps based on javascript  accelerate data import

As I proposed in https://github.com/graphite-project/graphite-web/issues/976

I've added a new datapoint format parameter with format XmsY , when you query data with this new parameter server will return series datapoints in a more suitable javascript format

X= time
Y=value
 [ X in timestamps in ms , Y] 

So if you do a query

```
http://<graphite>/render?format=json&from=-6h&until=now&target=aliasByNode(dwily.pro.c1.s1.nono.system.disk.sda.disk_octets.read,7)
```

you will get that.

image

else if you do this other query

```
http://<graphite>/render?format=json&jsondpfmt=XmsY&from=-6h&until=now&target=aliasByNode(dwily.pro.c1.s1.nono.system.disk.sda.disk_octets.read,7)
```

image

Now client side can support querys with this format and check if returned serie[i].dpfmt='XmsY' 

a) if returned,  the graphite server support new jsondpfmt parameter and can get data direct from retured json data. without need of reorder and transform X value.

b) else, the  server side is not yet supporting  jsondpfmt  parameter an server will return data in the old format  "YXs" ( default if no parameter  jsondpfmt  is queried)  and client side will have to reorder and transform data.

### CODE REVIEW

**Comment by brutasse** [comment]
@toni-moreno regarding metadata, if you address https://github.com/graphite-project/graphite-web/pull/980#issuecomment-59705231 and make it a *separate* pull request that includes docs and tests, I'm happy to consider it for inclusion. JSON format = 1 pull request, metadata = another pull request.

**Comment by toni-moreno** [comment]
Thank you @brutasse  to let me add this new features.

Correct me if I'm wrong

I should  make :

One PR adding parameter jsondpformat="XmsY"

````
http://<graphite>/render?format=json&jsondpformat=XmsY
```
And  another separate PR with new parameter generic metadata=xxxxx

````
http://<graphite>/render?format=json&metadata={true,cur,avg,max,min,sum}
```

Isn't it?

**Comment by toni-moreno** [comment]
Hi @brutasse I've finally leave this PR for the  jsondpformat parameter. I've also rebased it to have only one valid commit.

I will be enormously grateful if you could merge it.  ( I need  urgently to fix issues importing data with IE8 and  highcharts, ... that my customer has a requirement).

In next days I will do a new PR with parameter metadata as you suggested some weeks.

Thank you very much.

**Comment by brutasse** [comment]
@toni-moreno we're not going to rush a feature into an open source project because you have a customer requirement :) You can always maintain your fork while we're iterating on the feature.

`jsondpfmt`, `XmsY` and `YXs` still look too cryptic to me. No other committers have commented so I don't know how they feel about that change.

In any case this will also need tests, and since it touches a public HTTP API, docs need to be updated.

**Comment by obfuscurity** [comment]
I don't understand why adding this metadata can't be as simple as calling a single parameter, e.g. `verbose=1`, and any formats (json, csv, raw, etc) can be extended independently to support that. Why the focus on arcane tertiary params?

**Comment by toni-moreno** [comment]
Hi @brutasse Of course I hope you will merge it because  you think is a good improvement also for other dashboard projects and not for my customers.:wink:

Once merged,  I have plans to build a PR for this new parameter for grafana ( open source project at which I've already contributed).

@obfuscurity , I had focused , metadata only for json  based format, but we can open  a new discussion about  metadata if you wish in a new PR. I would like to contribute writing this code in the way you think is better for graphite, so will be grateful if you say me how do you like to query metadata and how do you expect to get response from graphite

**Comment by obfuscurity** [comment]
I'd fine with seeing this go in considering our recent additions for `format=dygraph` and `format=rickshaw` but I'm going to simplify it a bit.

**Comment by toni-moreno** [comment]
Hi @obfuscurity  , I'm happy to see your comment. feel free to simplify/refactors as your own PR.

Thank you very much

**Pull request closed without merging**
