### PR TITLE
Make sure timeShift(...) doesn't crash for non-existing series

### PR DESCRIPTION
**Pull request by zaptm**
Fixes https://github.com/graphite-project/graphite-web/issues/217

### CODE REVIEW

**Comment by duclet** [comment]
So I see this is merged into master all the way from 2013 but it was not merged in the 0.9.x branch which seems like the releases are tagged from. As such, this is still not working on the current version.

**Comment by deniszh** [comment]
I can backported it to 0.9.x, but please note that we have no plans to release 0.9.x anymore.

**Comment by duclet** [comment]
If you are not going to release it anymore, then it is fine. I've been trying to setup a graph that needs this feature and was surprised that a fix was merged into master in 2013 and with the current latest version didn't have the fix (don't see any other version besides the 0.9.x). If there will be a new version based on master soon, then I can wait. Thanks.

**Comment by jkandula** [comment]
Has this been part of any release yet? Thanks

**Comment by deniszh** [comment]
@jkandula: No, not yet. Made it a part of 0.9.16 milestone.
It's in the master branch, so, will be part of 1.0 release too - when it is done.

**Pull request merged**
