### PR TITLE
Remote merge performance fixes

### PR DESCRIPTION
**Pull request by iksaif**
See https://github.com/graphite-project/graphite-web/issues/1617

This restore previous performances when REMOTE_STORE_MERGE_RESULTS is enabled

### CODE REVIEW

**Comment by deniszh** [comment]
Does `setup.py` changes intended?

**Comment by iksaif** [comment]
Yes because I need this patch to be able to run the tests (https://github.com/graphite-project/graphite-web/pull/1666/commits/69b8da1679f0946691353920f5e07a272aa874d1). I can send if separately if you want.

**Comment by deniszh** [comment]
Ah, it's in a separate commit, missed that, sorry.
From my perspective, it looks good.
Tested on your prod, @iksaif ?
I think we can merge it if no other objections.
And then repeat perftest, @obfuscurity . :)

**Comment by obfuscurity** [comment]
A general note that this addresses performance regressions for `REMOTE_STORE_MERGE_RESULTS ` introduced in https://github.com/graphite-project/graphite-web/pull/1657.

**Comment by obfuscurity** [comment]
I'd like to see the `setup.py` changes submitted separately if you don't mind.

**Comment by obfuscurity** [comment]
@iksaif Can you share your before-and-after benchmarking results?

**Comment by iksaif** [comment]
3eef8bee501b4ef5a348a0eb16cfd3ee

I'll remove the setup.py changes right away.

**Comment by deniszh** [comment]
👍

**Comment by deniszh** [comment]
@iksaif - Could you please check if this fix still relevant after merging PR #1674 ?
I suspect that it still, because we still not filtering remote nodes, but maybe worth to check.

**Comment by iksaif** [comment]
Yes it is still relevant, the MutliReader should never make potentially AsynchronousReaders synchronous.

**Comment by deniszh** [comment]
Thanks!

**Pull request merged**
